### ISSUE TITLE
Failed to create a backup

### ISSUE THREAD

**Issue by Diegaco2005** [lavinir/hassio-onedrive-backup#1]
Hi!
I'm trying to use your addon to make backups on OneDrive, but in the first use I received a timeout error:

```
10/27/2022 12:09:35 Info: Checking backups
10/27/2022 12:09:36 Info: Retrieving existing online backups...
10/27/2022 12:09:37 Info: Creating new backup
10/27/2022 12:09:37 Info: Starting full local backup
10/27/2022 12:39:38 Error: Failed creating new backup. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 1800 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at hassio_onedrive_backup.Hass.HassioClient.CreateBackupAsync(String backupName, Boolean compressed, String password) in /src/Hass/HassioClient.cs:line 74
10/27/2022 12:39:38 Info: Online backups synced. No upload required
10/27/2022 12:39:41 Info: Interval Completed.
```

How I can solve this error and make the backup?
There's a way to retry the backup?

There's a plan to make partial backups in the future? Maybe with this option, timeout error will not occur.

**Comment by lavinir** [comment]
Hi, 

Thanks for opening. 

The Timeout configured is 30 minutes (I assumed that would be enough time for the backup to complete). 
I will export this value as optional configuration for users to be able to amend if necessary.  
Just to make sure, could you take a look at the supervisor logs - you should see a log for when the initial call to start the backup and one when it ended and see how long it actually took ?
The initial log should look something like this:
> Creating new full backup with slug XXXXXXX
and the log upon completion:
> Creating full backup with slug XXXXXX completed

Out of curiosity, what hardware are you running on?

**Comment by lavinir** [comment]
Thanks. Must be a large set up :) 
Looks like you're clocking in at 31 minutes for backup time just over the defined timeout. 
This should be fixed in the next update that will allow you to increase the timeout in the addon configuration. 

Aiming for an update in a couple of days.

**Comment by Diegaco2005** [comment]
Thanks for the quick return.
I have some GB's on Media folder, because its's stores the camera recordings. In my manual backups, I ignore this folder to generate a compact backup.

If the addon has the option to choose the backup folders, the timeout can be reduced in my case.

I'll wait for the next update, then I'll use this addon to finally automate my backups!

**Comment by lavinir** [comment]
v1.1 is out. You should be able to increase this value as needed in the configuration now.
