### ISSUE TITLE
upload failed: bad request

### ISSUE THREAD

**Issue by mariobrosch** [lavinir/hassio-onedrive-backup#107]
I have installed this addon, small partial backups uploaded succesfully, a full backup gives a bad request error. Please advise.

```
08/30/2023 10:19:58 [11] Info: Backup interval configured to every 24 hours
08/30/2023 10:19:58 [11] Info: File Sync Disabled
08/30/2023 10:20:00 [8] Info: Found 1 backups to upload.
08/30/2023 10:20:00 [8] Info: Uploading Full Backup 2023-08-30 09:59:34 (08/30/2023 09:59:34)
08/30/2023 10:20:00 [8] Info: Fetching Local Backup (Slug:89514d0b)
08/30/2023 10:21:15 [15] Info: Backup (89514d0b) fetched successfully
08/30/2023 10:21:22 [15] Error: Error uploading backup: Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: BadRequest
Message: Multiple action overloads were found with the same binding parameter for 'microsoft.graph.createUploadSession'.
Inner error:
	AdditionalData:
	date: 2023-08-30T08:21:22
	request-id: c86558b3-37d8-4bfe-980b-6da67e64f5e6
	client-request-id: c86558b3-37d8-4bfe-980b-6da67e64f5e6
ClientRequestId: c86558b3-37d8-4bfe-980b-6da67e64f5e6
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 143
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 238
```

**Comment by mariobrosch** [comment]
sorry, duplicate
