### ISSUE TITLE
Failed creating new backup. System.Threading.Tasks

### ISSUE THREAD

**Issue by konradwalsh** [lavinir/hassio-onedrive-backup#12]
Getting the following errors:

`````
11/28/2022 14:24:28 Info: Checking backups
11/28/2022 14:24:28 Info: Retrieving existing local backups...
11/28/2022 14:24:28 Info: Retrieving existing online backups...
11/28/2022 14:24:28 Info: Last local backup Date: None
11/28/2022 14:24:28 Info: Last online backup Date: 11/27/2022 14:02:12
11/28/2022 14:24:28 Info: Creating new backup
11/28/2022 14:24:28 Info: Starting partial local backup
11/28/2022 14:54:28 Error: Failed creating new backup. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 1800 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at hassio_onedrive_backup.Hass.HassioClient.CreateBackupAsync(String backupName, Boolean appendTimestamp, Boolean compressed, String password, IEnumerable`1 folders, IEnumerable`1 addons) in /src/Hass/HassioClient.cs:line 104
11/28/2022 14:54:28 Info: Online backups synced. No upload required
11/28/2022 14:54:30 Info: Interval Completed.
````


Any idea why?

My backups are 8gb in size

**Comment by lavinir** [comment]
This has already been fixed. see #1 
You can increase the timeout value in the [settings](https://github.com/lavinir/hassio-onedrive-backup#hass_api_timeout_minutes)
