### ISSUE TITLE
Frontend displays an error though the backup seems to be created

### ISSUE THREAD

**Issue by marcgarciamarti** [lavinir/hassio-onedrive-backup#131]
Hello,

for some reason, the frontend will display an error message about this addon being unable to create a local backup, although when I then go to the addon interface, the local backup is indeed there. Unfortunately dismissed the last frontend notification but I can upload it next time I trigger the backup manually, as I suspect I only see that message when the backup is triggered manually (can't say it for certain).

I don't know if I can fish that pop up message somewhere in the system. I'm attaching the log messages that I see in the addon section. I don't see anything connected with the issue that I'm trying to report, but now that I come to see these log messages, something seems to not be working smoothly, right?

thanks

```
10/07/2023 23:19:15 [1] Info: Anonymous Telemetry Disabled
10/07/2023 23:19:17 [7] Info: Creating new backup
10/07/2023 23:19:17 [7] Info: Starting partial local backup
10/07/2023 23:49:17 [34] Error: Backup request timed out. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 1800 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at hassio_onedrive_backup.Hass.HassioClient.CreateBackupAsync(String backupName, DateTime timeStamp, Boolean appendTimestamp, Boolean compressed, String password, IEnumerable`1 folders, IEnumerable`1 addons) in /src/Hass/HassioClient.cs:line 126
10/07/2023 23:49:17 [34] Error: Increase the timeout value in configuration
10/07/2023 23:49:17 [37] Info: Found 1 backups to upload.
10/07/2023 23:49:17 [37] Info: Uploading hass_backup_2023-10-07-11-15 (10/07/2023 11:15:55)
10/07/2023 23:49:17 [37] Info: Fetching Local Backup (Slug:063eb541)
10/07/2023 23:49:26 [40] Info: Backup (063eb541) fetched successfully
10/07/2023 23:49:27 [40] Info: Starting file upload. (Size:2104770560 bytes. Attempt: 1/3)
10/07/2023 23:53:28 [37] Info: Upload completed successfully
10/07/2023 23:59:27 [50] Info: Found 1 backups to upload.
10/07/2023 23:59:27 [50] Info: Uploading hass_backup_2023-10-07-23-19 (10/07/2023 23:19:17)
10/07/2023 23:59:27 [50] Info: Fetching Local Backup (Slug:578ad5f1)
10/07/2023 23:59:30 [54] Info: Backup (578ad5f1) fetched successfully
10/07/2023 23:59:51 [54] Info: Starting file upload. (Size:2106675200 bytes. Attempt: 1/3)
10/08/2023 00:03:33 [60] Info: Upload completed successfully
10/08/2023 17:10:22 [77] Info: Creating new backup
10/08/2023 17:10:22 [77] Info: Starting partial local backup
10/08/2023 17:40:22 [21] Error: Backup request timed out. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 1800 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at hassio_onedrive_backup.Hass.HassioClient.CreateBackupAsync(String backupName, DateTime timeStamp, Boolean appendTimestamp, Boolean compressed, String password, IEnumerable`1 folders, IEnumerable`1 addons) in /src/Hass/HassioClient.cs:line 126
10/08/2023 17:40:22 [21] Error: Increase the timeout value in configuration
10/08/2023 17:46:18 [32] Info: Found 1 backups to upload.
10/08/2023 17:46:18 [32] Info: Uploading hass_backup_2023-10-08-17-10 (10/08/2023 17:10:22)
10/08/2023 17:46:18 [32] Info: Fetching Local Backup (Slug:54c2ced7)
10/08/2023 17:46:21 [79] Info: Backup (54c2ced7) fetched successfully
10/08/2023 17:46:25 [79] Info: Starting file upload. (Size:2009712640 bytes. Attempt: 1/3)
10/08/2023 17:50:09 [77] Info: Upload completed successfully
```

**Comment by lavinir** [comment]
This is timeouts waiting for Home Assistant to create a backup - see [here ](https://github.com/lavinir/hassio-onedrive-backup#hass-api-timeout-minutes)on how to modify it.

**Comment by ahbrims** [comment]
I had same issue.   It may be useful if the error message included a hint that, the Hass api timeout setting may be too low, may cause this error message.

**Comment by lavinir** [comment]
This is already in the log actually. take a look at the log right after the exception above:
10/08/2023 17:40:22 [21] Error: Increase the timeout value in configuration

I guess it should be part of the original message. I'll make the change.

**Comment by marcgarciamarti** [comment]
Worked like a charm. Thanks!
