### ISSUE TITLE
Timeout 

### ISSUE THREAD

**Issue by derdustin1987** [lavinir/hassio-onedrive-backup#134]
ich have a problem with timeout. 

0/11/2023 00:00:03 [64] Info: Creating new backup
10/11/2023 00:00:03 [64] Info: Starting partial local backup
10/11/2023 00:30:03 [147] Error: Backup request timed out. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 1800 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at hassio_onedrive_backup.Hass.HassioClient.CreateBackupAsync(String backupName, DateTime timeStamp, Boolean appendTimestamp, Boolean compressed, String password, IEnumerable`1 folders, IEnumerable`1 addons) in /src/Hass/HassioClient.cs:line 126
10/11/2023 00:30:03 [147] Error: Increase the timeout value in configuration
10/11/2023 00:30:05 [152] Info: Creating new backup
10/11/2023 00:30:05 [152] Info: Starting partial local backup
10/11/2023 00:30:05 [152] Info: Backup complete
10/11/2023 00:35:05 [149] Info: Creating new backup
10/11/2023 00:35:05 [149] Info: Starting partial local backup
10/11/2023 00:35:05 [149] Info: Backup complete

**Comment by derdustin1987** [comment]
thx, but i cant find this option on settings. Version 2.2.2

**Comment by lavinir** [comment]
It's at the top, General section. Hass API timeout.

**Comment by derdustin1987** [comment]
Many thx :)
