### ISSUE TITLE
oneDrive quota reached, oneDrive addon continues to attempt to upload

### ISSUE THREAD

**Issue by ERBN19** [lavinir/hassio-onedrive-backup#140]
I have installed oneDrive version 2.2.3. 

I have reached my oneDrive quota due to an extremely growing HA database. The addon also tries to upload yesterday's backup, hence uploading 2 backups

Now the oneDrive addon continuously (every 5 minutes) tries to upload backup, but it always fails. At the time of writing, there are already again 25 notifications in HA's notification inbox.

**The Log:**
10/26/2023 16:47:02 [62] Info: Found 2 backups to upload.
10/26/2023 16:47:02 [62] Info: Uploading hass_backup_2023-10-26-14-51 (10/26/2023 14:51:55)
10/26/2023 16:47:02 [62] Info: Fetching Local Backup (Slug:ca7bcaa9)
10/26/2023 16:47:03 [63] Info: Backup (ca7bcaa9) fetched successfully
10/26/2023 16:47:04 [63] Info: Starting file upload. (Size:1106503680 bytes. Attempt: 1/3)
10/26/2023 16:50:56 [44] Error: Error uploading: Status Code: InsufficientStorage
Microsoft.Graph.ServiceException: Code: quotaLimitReached
Message: Insufficient Space Available
Throw site: 70dd.07f8
AdditionalData:
	localizedMessage: De opgegeven actie kan niet worden voltooid omdat de gebruiker de quotumlimiet heeft bereikt.
   at Microsoft.Graph.SimpleHttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.UploadSliceRequest`1.SendRequestAsync(Stream stream, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.UploadSliceRequest`1.PutAsync(Stream stream, CancellationToken cancellationToken)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadSliceAsync(UploadSliceRequest`1 uploadSliceRequest, ICollection`1 exceptionTrackingList)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 217
10/26/2023 16:50:56 [44] Info: Uploading hass_backup_2023-10-25-14-47 (10/25/2023 14:47:28)
10/26/2023 16:50:56 [44] Info: Fetching Local Backup (Slug:0fb8eab4)
10/26/2023 16:50:57 [44] Info: Backup (0fb8eab4) fetched successfully
10/26/2023 16:50:57 [44] Info: Starting file upload. (Size:1116723200 bytes. Attempt: 1/3)
10/26/2023 16:54:56 [60] Error: Error uploading: Status Code: InsufficientStorage
Microsoft.Graph.ServiceException: Code: quotaLimitReached
Message: Insufficient Space Available
Throw site: 70dd.07f8
AdditionalData:
	localizedMessage: De opgegeven actie kan niet worden voltooid omdat de gebruiker de quotumlimiet heeft bereikt.
   at Microsoft.Graph.SimpleHttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.UploadSliceRequest`1.SendRequestAsync(Stream stream, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.UploadSliceRequest`1.PutAsync(Stream stream, CancellationToken cancellationToken)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadSliceAsync(UploadSliceRequest`1 uploadSliceRequest, ICollection`1 exceptionTrackingList)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 217
10/26/2023 16:57:02 [68] Info: Found 2 backups to upload.
10/26/2023 16:57:02 [68] Info: Uploading hass_backup_2023-10-26-14-51 (10/26/2023 14:51:55)
10/26/2023 16:57:02 [68] Info: Fetching Local Backup (Slug:ca7bcaa9)
10/26/2023 16:57:04 [67] Info: Backup (ca7bcaa9) fetched successfully
10/26/2023 16:57:04 [67] Info: Starting file upload. (Size:1106503680 bytes. Attempt: 1/3)
10/26/2023 17:01:13 [68] Error: Error uploading: Status Code: InsufficientStorage
Microsoft.Graph.ServiceException: Code: quotaLimitReached
Message: Insufficient Space Available
Throw site: 70dd.07f8
AdditionalData:
	localizedMessage: De opgegeven actie kan niet worden voltooid omdat de gebruiker de quotumlimiet heeft bereikt.
   at Microsoft.Graph.SimpleHttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.UploadSliceRequest`1.SendRequestAsync(Stream stream, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.UploadSliceRequest`1.PutAsync(Stream stream, CancellationToken cancellationToken)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadSliceAsync(UploadSliceRequest`1 uploadSliceRequest, ICollection`1 exceptionTrackingList)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 217
10/26/2023 17:01:13 [68] Info: Uploading hass_backup_2023-10-25-14-47 (10/25/2023 14:47:28)
10/26/2023 17:01:13 [68] Info: Fetching Local Backup (Slug:0fb8eab4)
10/26/2023 17:01:15 [65] Info: Backup (0fb8eab4) fetched successfully
10/26/2023 17:01:15 [69] Info: Starting file upload. (Size:1116723200 bytes. Attempt: 1/3)
10/26/2023 17:05:14 [65] Error: Error uploading: Status Code: InsufficientStorage
Microsoft.Graph.ServiceException: Code: quotaLimitReached
Message: Insufficient Space Available
Throw site: 70dd.07f8
AdditionalData:
	localizedMessage: De opgegeven actie kan niet worden voltooid omdat de gebruiker de quotumlimiet heeft bereikt.
   at Microsoft.Graph.SimpleHttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.UploadSliceRequest`1.SendRequestAsync(Stream stream, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.UploadSliceRequest`1.PutAsync(Stream stream, CancellationToken cancellationToken)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadSliceAsync(UploadSliceRequest`1 uploadSliceRequest, ICollection`1 exceptionTrackingList)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 217
10/26/2023 17:07:03 [73] Info: Found 2 backups to upload.
10/26/2023 17:07:03 [73] Info: Uploading hass_backup_2023-10-26-14-51 (10/26/2023 14:51:55)
10/26/2023 17:07:03 [73] Info: Fetching Local Backup (Slug:ca7bcaa9)
10/26/2023 17:07:04 [77] Info: Backup (ca7bcaa9) fetched successfully
10/26/2023 17:07:04 [77] Info: Starting file upload. (Size:1106503680 bytes. Attempt: 1/3)
10/26/2023 17:11:01 [73] Error: Error uploading: Status Code: InsufficientStorage
Microsoft.Graph.ServiceException: Code: quotaLimitReached
Message: Insufficient Space Available
Throw site: 70dd.07f8
AdditionalData:
	localizedMessage: De opgegeven actie kan niet worden voltooid omdat de gebruiker de quotumlimiet heeft bereikt.
   at Microsoft.Graph.SimpleHttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.UploadSliceRequest`1.SendRequestAsync(Stream stream, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.UploadSliceRequest`1.PutAsync(Stream stream, CancellationToken cancellationToken)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadSliceAsync(UploadSliceRequest`1 uploadSliceRequest, ICollection`1 exceptionTrackingList)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 217

**Comment by lavinir** [comment]
Maybe I could add a check prior to uploading to see how much available storage exists, but I would still need to surface the error.
What behavior would you have expected here ?

**Comment by ERBN19** [comment]
In my situation, I created a separate oneDrive for the HA, which has a storage capacity of up to 5GB.

As described, my database (had) become very large, around the 1.5GB file. There were 3 files uploaded to the oneDrive and they took up about 4 GB of storage. The 4 and 5 were also large, but there was no longer room for them.

This resulted in the addOn always making a new attempt to send the backup to the oneDrive folder. However, this always failed on the previously given log message. The result was that the addOn gave a notification in the HA inbox. However, because the addOn kept trying every 5 minutes, a constant stream of notifications arrived in the HA inbox.

A pre-check would be a solution or a number of attempts and if these fail the process will stop. This so that the constant flow of notifications stops. At this point I have the database back under control and decreased the size, so this post is now more informational to improve the addOn.

**Comment by lavinir** [comment]
I will add a precheck, btw, you could also disable persistent notifications in the settings.
