### ISSUE TITLE
Warning: Local backup could nit be gerenerated, but it is there

### ISSUE THREAD

**Issue by Falfango** [lavinir/hassio-onedrive-backup#149]
I got every day the warning from HA, that a local backup could not be generated. When I look at the backups, the local and the onedrive backup are there. This starts, when I set keep local backups to 10 and keep onedrive backups to 50. There was no change in behaviour, when I chaged it to the same numbers like it was before. HA and all modules are at the newest versions.

The logs are

11/16/2023 20:52:49 [44] Info: Creating new backup
11/16/2023 20:52:49 [44] Info: Starting full local backup
11/16/2023 21:22:49 [61] Error: Backup request timed out (Increase the Hass API timeout in settings to fix). System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 1800 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at hassio_onedrive_backup.Hass.HassioClient.CreateBackupAsync(String backupName, DateTime timeStamp, Boolean appendTimestamp, Boolean compressed, String password, IEnumerable`1 folders, IEnumerable`1 addons) in /src/Hass/HassioClient.cs:line 126
11/16/2023 21:22:55 [61] Info: Creating new backup
11/16/2023 21:22:55 [61] Info: Starting full local backup
11/16/2023 21:22:55 [61] Info: Backup complete
11/16/2023 21:27:56 [39] Info: Found 1 backups to upload.
11/16/2023 21:27:56 [19] Info: Uploading hass_backup_2023-11-16-20-52 (11/16/2023 20:52:49)
11/16/2023 21:27:56 [19] Info: Fetching Local Backup (Slug:5f5807a6)
11/16/2023 21:28:05 [29] Info: Backup (5f5807a6) fetched successfully
11/16/2023 21:28:06 [29] Info: Starting file upload. (Size:1328332800 bytes. Attempt: 1/3)
11/16/2023 21:36:09 [41] Info: Upload completed successfully

**Comment by mrkaqz** [comment]
I have same problem got alert on persistent notification that cannot create back up but when look into the webUI the back up is there. 

Here is the log.

-------------------------------------------------------------------

11/21/2023 19:15:18 [1] Info: Anonymous Telemetry Disabled
11/21/2023 19:15:18 [1] Info: Backup interval configured to every 24 hours
11/21/2023 19:15:18 [1] Info: Generational backups enabled
11/21/2023 19:15:40 [5] Info: Creating new backup
11/21/2023 19:15:40 [5] Info: Starting full local backup
11/21/2023 19:15:40 [5] Info: Backup complete
11/21/2023 19:20:40 [17] Info: Creating new backup
11/21/2023 19:20:40 [17] Info: Starting full local backup
11/21/2023 20:20:40 [54] Error: Backup request timed out (Increase the Hass API timeout in settings to fix). System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 3600 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at hassio_onedrive_backup.Hass.HassioClient.CreateBackupAsync(String backupName, DateTime timeStamp, Boolean appendTimestamp, Boolean compressed, String password, IEnumerable`1 folders, IEnumerable`1 addons) in /src/Hass/HassioClient.cs:line 126
11/21/2023 20:20:51 [56] Info: Creating new backup
11/21/2023 20:20:51 [56] Info: Starting full local backup
11/21/2023 20:20:51 [56] Info: Backup complete
11/21/2023 20:25:53 [60] Info: Creating new backup
11/21/2023 20:25:53 [60] Info: Starting full local backup
11/21/2023 20:25:53 [60] Info: Backup complete
11/21/2023 20:30:54 [65] Info: Creating new backup
11/21/2023 20:30:54 [65] Info: Starting full local backup
11/21/2023 20:30:54 [65] Info: Backup complete
11/21/2023 20:35:55 [69] Info: Creating new backup
11/21/2023 20:35:55 [69] Info: Starting full local backup
11/21/2023 20:35:55 [63] Info: Backup complete
11/21/2023 20:40:55 [72] Info: Creating new backup
11/21/2023 20:40:55 [72] Info: Starting full local backup
11/21/2023 20:40:55 [72] Info: Backup complete
11/21/2023 20:45:56 [75] Info: Creating new backup
11/21/2023 20:45:56 [75] Info: Starting full local backup
11/21/2023 20:45:56 [75] Info: Backup complete
11/21/2023 20:50:57 [69] Info: Found 1 backups to upload.
11/21/2023 20:50:57 [69] Info: Uploading hass_backup_2023-11-21-19-20 (11/21/2023 19:20:40)
11/21/2023 20:50:57 [69] Info: Fetching Local Backup (Slug:d991cd06)
11/21/2023 20:51:20 [82] Info: Backup (d991cd06) fetched successfully
11/21/2023 20:51:21 [82] Info: Starting file upload. (Size:9538344960 bytes. Attempt: 1/3)
11/21/2023 21:21:47 [71] Info: Upload completed successfully
11/21/2023 21:21:47 [71] Info: Reached Max Online Backups (10)
11/21/2023 21:21:47 [79] Info: Found 1 backups to delete from OneDrive.
11/21/2023 21:21:47 [79] Info: Deleting item: Full_Backup_2023-11-12_130000.tar
11/21/2023 21:21:48 [71] Info: Reached Max Local Backups (2)
11/21/2023 21:21:48 [71] Info: Removing 1 local backups

**Comment by lavinir** [comment]
Yeah so if you look at the first error log, it tells you the problem and the fix. For large backups the API call to to create it could time out with the default value. You have the option to increase this in the addon settings.
The reason you see the backup created is that the backup trigger does go through but does not return a response in time to the addon because of the timeout.. 

Increasing the timeout value should make resolve the error.

**Comment by Falfango** [comment]
Thanks. I haven't noticed, that I could change the timeout bymyself.
