### ISSUE TITLE
Uploads fail with bad request.

### ISSUE THREAD

**Issue by fransfr** [lavinir/hassio-onedrive-backup#150]
Yesterday I installed the app and validated with MS. That all went smoothly, however the upload doesn't work.

After reading some other issues I decided to re-install the app which was again no problem. Authenticated with MS and hoped to get it working now. But again same  issue. The backup is created locally but the upload fails. This is the info from the log file:

[1] Info: No new settings file. Attempting to restore from legacy configuration
11/23/2023 17:14:35 [1] Info: Anonymous Telemetry Disabled
11/23/2023 17:14:35 [1] Info: Backup interval configured to every 24 hours
11/23/2023 17:14:35 [1] Warning: Token cache is empty
11/23/2023 17:14:36 [5] Info: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code GHNTRM6X9 to authenticate.
11/23/2023 17:16:42 [20] Info: Creating new backup
11/23/2023 17:16:42 [20] Info: Starting full local backup
11/23/2023 17:16:58 [22] Info: Backup complete
11/23/2023 17:17:07 [22] Info: Uploading hass_backup_2023-11-23-17-16 (11/23/2023 17:16:42)
11/23/2023 17:17:07 [22] Info: Fetching Local Backup (Slug:a6015769)
11/23/2023 17:17:07 [20] Info: Backup (a6015769) fetched successfully
11/23/2023 17:17:07 [20] Error: Error uploading backup: Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: invalidRequest
Message: Invalid request
Inner error:
	AdditionalData:
	date: 2023-11-23T16:17:07
	request-id: f1f22b9b-72d7-40cd-ba60-181d72976c36
	client-request-id: f1f22b9b-72d7-40cd-ba60-181d72976c36
ClientRequestId: f1f22b9b-72d7-40cd-ba60-181d72976c36

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 151
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 361

**Comment by lavinir** [comment]
Hi,

This type of error is usually related to 'invalid chars' in the backup filename. I added a fix a couple of versions back that should be replacing those chars but maybe something was missed.
* Is this happening for all backups?
* Are these backups created by the addon ?
* Could you try using a simple name just to rule this issue out and trigger a backup manually from the addon (e.g. backup_test as the name?)

**Comment by fransfr** [comment]
Hi, the name I used was hass_backup. In OneDrive backup I click on Trigger backup. The backup is on local, when I click on Upload I get an error at the bottom of the screen "An error has occured. This application may no longer respond until reloaded. Reload".

A friend of mine is using it too, and he showed me a screenshot how to edit the config file with YAML. But when I click on "Configuration" it says "This add-on has no configuration".

I changed the name for the backup to HABackup, but it makes no difference.

**Comment by fransfr** [comment]
I once more did an uninstall, complete reboot and installed it once more, but it makes no difference.

**Comment by lavinir** [comment]
Yaml config settings are deprecated so it makes sense you have nothing there.
Your backup name is fine. 
* What do you have set under "Backup Instance Name" ?
* Can you try enabling File Sync and trying to get some file uploaded to OneDrive to rule out a global upload issue ?

**Comment by fransfr** [comment]
I used all defaults, so Backup Instance Name was blank, but using a name makes no difference either.
I modified a word document and it was nicely synced on onedrive.

**Comment by lavinir** [comment]
Could you try a couple of things:
1. Enable watching all backups and choose to upload a simple upgrade backup made by Home Assistant ,see if that goes through
2. For the failed backups - Enable Verbose logging and share the logs from creating a backup to the upload part. (Specifically I want to see some logs during creation so not just the upload part).

**Comment by fransfr** [comment]
This is regarding 2.
12/01/2023 11:41:56 [74] Info: Creating new backup
12/01/2023 11:41:56 [74] Info: Starting full local backup
12/01/2023 11:42:01 [83] Verbose: Checking backups
12/01/2023 11:42:01 [83] Verbose: Backup Interval Completed.
12/01/2023 11:42:12 [74] Info: Backup complete
12/01/2023 11:44:38 [108] Info: Uploading hass_backup_2023-12-01-11-41 (12/01/2023 11:41:56)
12/01/2023 11:44:38 [108] Info: Fetching Local Backup (Slug:d6b5afb8)
12/01/2023 11:44:38 [93] Info: Backup (d6b5afb8) fetched successfully
12/01/2023 11:44:38 [93] Verbose: Backup Description: {"Slug":"d6b5afb8","BackupDate":"2023-12-01T11:41:56.105764+01:00","InstanceName":"Frans","IsProtected":false,"Size":72.32,"BackupType":"full","Addons":[],"Folders":["share","addons/local","ssl","media"]}
12/01/2023 11:44:39 [93] Error: Error uploading backup: Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: invalidRequest
Message: Invalid request
Inner error:
	AdditionalData:
	date: 2023-12-01T10:44:39
	request-id: 090b76cb-b7bb-4488-bb1d-606c31e93f9b
	client-request-id: 090b76cb-b7bb-4488-bb1d-606c31e93f9b
ClientRequestId: 090b76cb-b7bb-4488-bb1d-606c31e93f9b

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 151
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 361
   
   
   
  What puzzles me is that this info remains completely empty:
  
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/20406920/38b2a4f9-25e7-4ec8-8c46-f3c686747455)

**Comment by amedeop** [comment]
The same for me.
Backup is not uploaded.

**Comment by kroessig** [comment]
Unfortunately for me too.

12/01/2023 21:10:49 [35] Info: Uploading hass_backup_2023-12-01-20-51 (12/01/2023 20:51:33)
12/01/2023 21:10:49 [35] Info: Fetching Local Backup (Slug:697a3b81)
12/01/2023 21:10:53 [32] Info: Backup (697a3b81) fetched successfully
12/01/2023 21:10:55 [37] Error: Error uploading backup: Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: invalidRequest
Message: Invalid request
Inner error:
	AdditionalData:
	date: 2023-12-01T20:10:55
	request-id: 35d530ae-3ad2-4950-bada-353c1328906d
	client-request-id: 35d530ae-3ad2-4950-bada-353c1328906d
ClientRequestId: 35d530ae-3ad2-4950-bada-353c1328906d

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 151
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 361

**Comment by lavinir** [comment]
Thanks. MS really need better error responses..
Could you check the OneDrive backup folder and see if a backup with the same name already exists there ? If it does try to delete it and see if upload goes through.

**Comment by iEddy1985** [comment]
I am having the same Problem, even after reinstalling. Would love to use the addon. Good Luck!

Logs:

[1] Info: No new settings file. Attempting to restore from legacy configuration
12/21/2023 13:37:41 [1] Info: Anonymous Telemetry Disabled
12/21/2023 13:37:41 [1] Info: Backup interval configured to every 24 hours
12/21/2023 13:37:41 [1] Warning: Token cache is empty
12/21/2023 13:37:44 [9] Info: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DBGTY6UYZ to authenticate.
12/21/2023 13:39:38 [17] Info: Uploading hass_backup_2023-12-21-13-21 (12/21/2023 13:21:30)
12/21/2023 13:39:38 [17] Info: Fetching Local Backup (Slug:0e5a7a9f)
12/21/2023 13:39:39 [16] Info: Backup (0e5a7a9f) fetched successfully
12/21/2023 13:39:47 [17] Error: Error uploading backup: Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: invalidRequest
Message: Invalid request
Inner error:
	AdditionalData:
	date: 2023-12-21T12:39:47
	request-id: 780c68e2-b990-4246-851a-6458302a819b
	client-request-id: 780c68e2-b990-4246-851a-6458302a819b
ClientRequestId: 780c68e2-b990-4246-851a-6458302a819b

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 151
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 361

**Comment by AlexFiete** [comment]
sam problem for me

**Comment by lavinir** [comment]
Update: I am working on the next version which will include updates to the underlying MS Graph libraries used to work with OneDrive. Along with that I will add better debug logging so that if this remains it will at least make it easier to understand what's happening.
