### ISSUE TITLE
Upload to OneDrive fails

### ISSUE THREAD

**Issue by jaripetteri** [lavinir/hassio-onedrive-backup#202]
Having issues to upload backups to OneDrive, local backups are generated but not uploades. Doesn't give other errors but found this on logs. My other install with totaly different Onedrive works fine. What might be the issue?

`04/14/2024 12:32:59 [56] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 228
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 399
04/14/2024 12:32:59 [56] Info: Uploading saaristo_hass_backup_2024-04-14-01-20 (04/14/2024 01:20:27)
04/14/2024 12:32:59 [56] Info: Fetching Local Backup (Slug:0ecff8e3)
04/14/2024 12:33:00 [55] Info: Backup (0ecff8e3) fetched successfully
04/14/2024 12:33:02 [59] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 228
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 399
04/14/2024 12:37:57 [56] Info: Found 2 backups to upload.
04/14/2024 12:37:57 [56] Info: Uploading saaristo_hass_backup_2024-04-14-11-44 (04/14/2024 11:44:50)
04/14/2024 12:37:57 [56] Info: Fetching Local Backup (Slug:916d91ea)
04/14/2024 12:37:58 [65] Info: Backup (916d91ea) fetched successfully
`

**Comment by lavinir** [comment]
Was this working before on this instance ?
Could you change logging to Verbose and send the the logs containing the backup description before upload? 
The log begins with: "Backup Description:..."

**Comment by jaripetteri** [comment]
No, this one is a new setup and haven't work before so maybe I have just missed some setting there.

`04/15/2024 10:33:55 [78] Verbose: Backup Description: {"Slug":"916d91ea","BackupDate":"2024-04-14T11:44:50.2182+03:00","InstanceName":null,"IsProtected":true,"Size":961.5,"BackupType":"full","Addons":[],"Folders":["share","addons/local","ssl","media"]}
04/15/2024 10:33:56 [78] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 228
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 399
04/15/2024 10:33:56 [78] Verbose: Backup size to upload: 1.01GB
04/15/2024 10:33:56 [78] Info: Uploading saaristo_hass_backup_2024-04-14-01-20 (04/14/2024 01:20:27)
04/15/2024 10:33:56 [78] Info: Fetching Local Backup (Slug:0ecff8e3)
04/15/2024 10:33:57 [102] Info: Backup (0ecff8e3) fetched successfully
04/15/2024 10:33:58 [102] Verbose: Backup Description: {"Slug":"0ecff8e3","BackupDate":"2024-04-14T01:20:27.078634+03:00","InstanceName":null,"IsProtected":true,"Size":1006.16,"BackupType":"full","Addons":[],"Folders":["share","addons/local","ssl","media"]}
04/15/2024 10:33:59 [102] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 228
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 399
04/15/2024 10:34:00 [102] Verbose: Evaluating Online Generational Backups
04/15/2024 10:34:00 [102] Verbose: Found 0 OneDrive backups that can be removed (Generational Rules)
04/15/2024 10:34:00 [102] Verbose: Evaluating Local Generational Backups
04/15/2024 10:34:00 [102] Verbose: Backup (916d91ea (04/14/2024 11:44:50) retained for Generational Daily policy local
04/15/2024 10:34:00 [102] Verbose: Backup (0ecff8e3 (04/14/2024 01:20:27) retained for Generational Daily policy local
04/15/2024 10:34:00 [102] Verbose: Backup (916d91ea (04/14/2024 11:44:50) retained for Generational Weekly policy local
04/15/2024 10:34:00 [102] Verbose: Backup (916d91ea (04/14/2024 11:44:50) retained for Generational Monthly policy local
04/15/2024 10:34:00 [102] Verbose: Backup (916d91ea (04/14/2024 11:44:50) retained for Generational Yearly policy local
04/15/2024 10:34:00 [102] Verbose: Found 0 local backups that can be removed (Generational Rules)
04/15/2024 10:34:00 [102] Verbose: Ignoring 'External' backup: addon_a0d7b954_influxdb_4.6.0
04/15/2024 10:34:00 [102] Verbose: Ignoring 'External' backup: addon_a0d7b954_grafana_8.2.2
04/15/2024 10:34:00 [102] Verbose: Ignoring 'External' backup: hass_backup_2024-04-14-11-52
04/15/2024 10:34:00 [102] Verbose: Ignoring 'External' backup: hass_backup_2024-04-07-16-55
04/15/2024 10:34:00 [102] Verbose: Ignoring 'External' backup: core_2023.1.7
04/15/2024 10:34:00 [102] Verbose: Ignoring 'External' backup: 30. maaliskuuta 2024
04/15/2024 10:34:00 [102] Verbose: Ignoring 'External' backup: 30. syyskuuta 2023
04/15/2024 10:34:00 [102] Verbose: Ignoring 'External' backup: addon_5c53de3b_esphome_2022.12.8
04/15/2024 10:38:54 [72] Verbose: Checking backups
04/15/2024 10:38:54 [72] Verbose: Refreshing existing backups...
04/15/2024 10:38:54 [72] Verbose: Backup Interval Completed.
04/15/2024 10:38:54 [72] Verbose: Ignoring 'External' backup: addon_a0d7b954_influxdb_4.6.0
04/15/2024 10:38:54 [72] Verbose: Ignoring 'External' backup: addon_a0d7b954_grafana_8.2.2
04/15/2024 10:38:54 [72] Verbose: Ignoring 'External' backup: hass_backup_2024-04-14-11-52
04/15/2024 10:38:54 [72] Verbose: Ignoring 'External' backup: hass_backup_2024-04-07-16-55
04/15/2024 10:38:54 [72] Verbose: Ignoring 'External' backup: core_2023.1.7
04/15/2024 10:38:54 [72] Verbose: Ignoring 'External' backup: 30. maaliskuuta 2024
04/15/2024 10:38:54 [72] Verbose: Ignoring 'External' backup: 30. syyskuuta 2023
04/15/2024 10:38:54 [72] Verbose: Ignoring 'External' backup: addon_5c53de3b_esphome_2022.12.8
04/15/2024 10:38:55 [48] Verbose: Last local backup Date: 04/14/2024 11:44:50
04/15/2024 10:38:55 [48] Verbose: Last online backup Date: None
04/15/2024 10:38:55 [48] Info: Found 2 backups to upload.
04/15/2024 10:38:55 [48] Verbose: Backup size to upload: 0.96GB
04/15/2024 10:38:55 [48] Info: Uploading saaristo_hass_backup_2024-04-14-11-44 (04/14/2024 11:44:50)
04/15/2024 10:38:55 [48] Info: Fetching Local Backup (Slug:916d91ea)
04/15/2024 10:38:56 [11] Info: Backup (916d91ea) fetched successfully
`

**Comment by lavinir** [comment]
I don't think you missed any settings but I'm also not certain what's causing this. It is a low level error coming from the call to the Graph OneDrive API. 
Compared to your previous setup, this is just another personal Microsoft account ? 
Could you maybe try and use the previous account (using a separate "Instance Name" in the settings  so you don't overlap with the other one's backups? And no File Syncs as well)

**Comment by jaripetteri** [comment]
Yes, this is totally separate setup. Working one is my own HA installation and this one is on my parents house. Different HA, different MS account and so on. Only difference I can think off to my other (working) setup is that this one is behind 4G LTE network but shouldn't affect on this anyway.

I tried to install backup add on again but same result. I'll try other MS account later.

Also noted that OneDrive is not backing up Windows files which I thought was configured so might be something wrong on OneDrive side on that account.

**Comment by lavinir** [comment]
Hey @jaripetteri , was this issue closed intentionally?

**Comment by jaripetteri** [comment]
Actually not but can be closed as failure is on my MS account somehow. With another account it is working as it should. I haven't figured it out yet why but I can use the another MS account so no problem.

**Comment by pawellygan** [comment]
I have same problem here. New install, HA on different that 8123 port but port is exposed to internet.
