### ISSUE TITLE
Error uploading backup - basic functionality does not work

### ISSUE THREAD

**Issue by Zataras** [lavinir/hassio-onedrive-backup#203]
I followed configuration instructions. Application has rights to access my private onedrive space. However not a single time it was able to upload backup to cloud. Waited from yesterday so maybe some setting must propagate, but it seems that not.
Backup file is smaller than 60MB. I got plenty of free space in onedrive.
Can you help to fix it?
Logs below.

```
04/19/2024 08:41:02 [75] Info: Found 1 backups to upload.
04/19/2024 08:41:02 [75] Info: Uploading hass_backup_2024-04-18-11-58 (04/18/2024 11:58:31)
04/19/2024 08:41:02 [75] Info: Fetching Local Backup (Slug:2740ad10)
04/19/2024 08:41:02 [70] Info: Backup (2740ad10) fetched successfully
04/19/2024 08:41:03 [70] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 228
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 399
04/19/2024 08:43:14 [56] Info: Uploading hass_backup_2024-04-18-11-58 (04/18/2024 11:58:31)
04/19/2024 08:43:14 [56] Info: Fetching Local Backup (Slug:2740ad10)
04/19/2024 08:43:14 [29] Info: Backup (2740ad10) fetched successfully
04/19/2024 08:43:15 [29] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 228
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 399
```

**Comment by lavinir** [comment]
This is an error in the underlying MS SDK. It's not clear to me exactly what might be causing this.
Someone else opened an issue with this error a week ago as well here #202 .
Can you share more details about your setup - OS, network, any firewall / proxies outbound ?

**Comment by lavinir** [comment]
Closing as duplicate - tracking in #209
