### ISSUE TITLE
Just deployed but am seeing errors...

### ISSUE THREAD

**Issue by danielbrunt57** [lavinir/hassio-onedrive-backup#206]
Installation appeared to complete successfully but sync to OneDrive is stuck.
This is the sidebar view:

![image](https://github.com/lavinir/hassio-onedrive-backup/assets/49846893/2172f437-dc1f-4a98-9c54-149c22858e06)

Here is the log from the add-on:
```
 [1] Info: No new settings file. Attempting to restore from legacy configuration
04/24/2024 05:41:19 [10] Info: Anonymous Telemetry Disabled
04/24/2024 05:41:19 [10] Info: Backup interval configured to every 24 hours
04/24/2024 05:41:19 [10] Warning: Token cache is empty
04/24/2024 05:41:22 [4] Info: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DMETKUXYA to authenticate.
04/24/2024 05:43:23 [4] Error: Error getting free space: Microsoft.Graph.Models.ODataErrors.ODataError: Access denied
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Drive.DriveRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetFreeSpaceInGB() in /src/Graph/GraphHelper.cs:line 243
04/24/2024 05:43:23 [19] Error: accessDenied: Access denied
04/24/2024 05:48:24 [32] Error: Error getting free space: Microsoft.Graph.Models.ODataErrors.ODataError: Access denied
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Drive.DriveRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetFreeSpaceInGB() in /src/Graph/GraphHelper.cs:line 243
04/24/2024 05:48:24 [29] Error: accessDenied: Access denied
04/24/2024 05:48:51 [33] Error: accessDenied: Access denied
```

**Comment by danielbrunt57** [comment]
Ahgh!  I was using my Office 365 Business OneDrive (which has 1 TB).  I switched to my MS personal OneDrive (5GB) and it worked but I can only store 2 full backups (2GB each) there...
