### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by ledeckyr** [lavinir/hassio-onedrive-backup#233]
Hello, 
I set One Drive backup on my HA instalation. I use N100 PC with Proxmox virtualization and HAOS. I have only one virtual machine on it. Beffor start of backup rutine is memory allocated memory for 2,5GB. After the start of backup is here a peak to 5,6 GB and after backup is released only 1GB. In the log I see this errors. Can you help me with the analysis, please?
Best regards
Radek

10/03/2024 06:12:12 [4] Info: Anonymous Telemetry Disabled
10/03/2024 06:12:12 [4] Info: Backup interval configured to every 24 hours
10/03/2024 06:12:12 [4] Info: Generational backups enabled
10/03/2024 14:48:14 [39] Error: Error getting free space: System.Net.Http.HttpRequestException: Resource temporarily unavailable (graph.microsoft.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.HeadersInspectionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.CompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetHttpResponseMessage(RequestInformation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, String claims, Boolean isStreamResponse)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Drive.DriveRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetFreeSpaceInGB() in /src/Graph/GraphHelper.cs:line 258
10/03/2024 18:48:36 [24] Info: Creating new backup
10/03/2024 18:48:36 [24] Info: Starting full local backup
10/03/2024 18:48:49 [37] Info: Backup complete
10/03/2024 18:48:49 [37] Info: Found 1 backups to upload.
10/03/2024 18:48:49 [37] Info: Uploading hass_backup_2024-10-03-18-48 (10/03/2024 18:48:36)
10/03/2024 18:48:49 [37] Info: Fetching Local Backup (Slug:3e481cf1)
10/03/2024 18:48:49 [51] Info: Backup (3e481cf1) fetched successfully
10/03/2024 18:48:51 [24] Info: Starting file upload. (Size:683612160 bytes. Attempt: 1/3)
10/03/2024 18:51:08 [51] Info: Upload completed successfully
10/03/2024 18:51:08 [24] Info: Reached Max Online Backups (10)
10/03/2024 18:51:08 [24] Info: Found 1 backups to delete from OneDrive.
10/03/2024 18:51:08 [24] Info: Deleting item: hass_backup_2024-09-23-11-04.tar
10/03/2024 18:51:09 [24] Info: Reached Max Local Backups (10)
10/03/2024 18:51:09 [24] Info: Removing 1 local backups
10/03/2024 19:17:31 [4] Info: Anonymous Telemetry Disabled
10/03/2024 19:17:31 [4] Info: Backup interval configured to every 24 hours
10/03/2024 19:17:31 [4] Info: Generational backups enabled

**Comment by lavinir** [comment]
Are you saying the memory increase occurs only during the backup process ?
The upload shouldn't be doing this. If it's the backup itself this is not related to the addon, this is Home Assistant backing up.

You could try just triggering a backup directly from Home Assistant (you can stop the addon if you want to completely isolate the issue) and see what happens to your memory.

**Comment by ledeckyr** [comment]
Because my PC died on Saturday (SSD disk) is not possible to try it on original HW now. I started HA on W11 in virtual box and I will monitor it.
Thanks
Radek
