### ISSUE TITLE
Initializing... Error getting free space: Microsoft.Graph.Models.ODataErrors.ODataError: Access denied

### ISSUE THREAD

**Issue by gRiMMi83** [lavinir/hassio-onedrive-backup#239]
Hi, i tryed your onedrive backup with a personal and a business onedrive account, it's not working for me.
any solution?

10/16/2024 09:41:37 [15] Error: Error getting free space: Microsoft.Graph.Models.ODataErrors.ODataError: Access denied
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Drive.DriveRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetFreeSpaceInGB() in /src/Graph/GraphHelper.cs:line 243
10/16/2024 09:41:37 [15] Error: accessDenied: Access denied
10/16/2024 09:46:37 [25] Error: Error getting free space: Microsoft.Graph.Models.ODataErrors.ODataError: Access denied
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Drive.DriveRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetFreeSpaceInGB() in /src/Graph/GraphHelper.cs:line 243
10/16/2024 09:46:37 [25] Error: accessDenied: Access denied

**Comment by Patrice3122** [comment]
I encountered a persistent issue while trying to sign in, regardless of the browser or mode I used. Initially, I attempted to log in through both the standard and private modes of Microsoft Edge and Google Chrome. Unfortunately, each attempt resulted in the same error:

**Error: accessDenied: Access denied.**

To rule out any potential interference from other accounts or sessions, I built a Lubuntu virtual machine (VM) and repeated the process using the pre-installed Firefox browser. Even in this fresh environment, the issue persisted, leading to the same access denied error.

Here's a summary of the account setup:
 - **Personal Microsoft** account created specifically for backup purposes.
 - **Microsoft subscription** is shared with this dedicated account to increase storage capacity.
 - **Multi-Factor Authentication (MFA)** is enabled for this account.
 
I will appreciate any suggestion regarding this issue.

**Comment by THW712** [comment]
I am experiencing exactly the same issue. I have no idea how to resolve this. Thank you

**Comment by tamerhamdyelsayed** [comment]
same error for me

**Comment by MightyMaster** [comment]
Same error for me. Any Solutions?

**Comment by deviantintegral** [comment]
> Do you know how I can entirely uninstall the add-on?

I believe this addon stores everything inside the default addon data directory, so uninstalling it even in the UI should clean everything up. Even though it maps all the directories as `rw`, I don't see any evidence of config files in `config`.

I had this addon running for many months and only started seeing this issue in the last month or two. For anyone setting up new, I think this affects all users and isn't likely to be related to how you're setting it up.

**Comment by deviantintegral** [comment]
For anyone looking to get backups up and running, I was able to back up to OneDrive using the rclone addon: https://github.com/jcwillox/hassio-rclone-backup?tab=readme-ov-file

It is not quite a polished, and I could only get it to work by running `rclone config` locally and copying the config up to Home Assistant. But, it works!

**Comment by SmilyHM** [comment]
Thank you @deviantintegral,

I'll have a look. 👍 

I don't expect problems to be resolved or analyzed immediately -especially since these are mostly private projects- but no response at all is unfortunately unsatisfactory. There are already several reports about the current problems. A "I don't have much time at the moment, I'll take a look at it as soon as I have time again" would be enough for me. It's a shame that HA hasn't already equipped its own backup function with various cloud options.

**Comment by lavinir** [comment]
Issue has been found. See details here: #247
