### ISSUE TITLE
OneDrive initialization doesn't work

### ISSUE THREAD

**Issue by luctv1** [lavinir/hassio-onedrive-backup#241]
Hello,

I added the Addon and tried to configure it. I already granted the Plugin the access to my OneDrive with this Code.

But it won't stop with the initialization. I already restarted the addon, restarted HA and reinstalled the plugin.

![image](https://github.com/user-attachments/assets/7f340669-ef80-488e-8fc5-a581de367e79)

Here are my logs if this is helping:
`10/17/2024 08:56:38 [43] Error: Error getting free space: Microsoft.Graph.Models.ODataErrors.ODataError: Access denied
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Drive.DriveRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetFreeSpaceInGB() in /src/Graph/GraphHelper.cs:line 243
10/17/2024 08:56:39 [35] Error: accessDenied: Access denied`

I can see that the access to somewhere is denied but I already authenticated the access to OneDrive.

I hope someone can solve my problem

**Comment by Growianer** [comment]
Same here. Last Backup 20241104

**Comment by lavinir** [comment]
Issue has been found. See details here: #247
