### ISSUE TITLE
Add-on keeps giving error

### ISSUE THREAD

**Issue by StaffordBully** [lavinir/hassio-onedrive-backup#245]
Hi,
my add-on keeps giving errors
every few days the add-on stops working and i need to restart it.

![image](https://github.com/user-attachments/assets/027d02e5-478b-48d4-bbee-f7ffdb0e8ad5)

Greetings Bart

**Comment by Diegaco2005** [comment]
I have same issue. In logs, has an access denied error:

```
11/07/2024 13:45:55 [120] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Access denied
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Drive.DriveRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 228
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 399
11/07/2024 13:45:56 [120] Error: accessDenied: Access denied
```

**Comment by StaffordBully** [comment]
I have deleted the addon and reinstalled it but same results. Hope it will be fixed soon

**Comment by SmilyHM** [comment]
Same here. Last Backup 20241103 (backup every two days at 4 a.m.)

**Comment by J-escandon** [comment]
Same with me

**Comment by MantasGSXR** [comment]
I have the same problem on a new installation. Other install seems to be doing just fine.

**Comment by mrochette01** [comment]
Same with me

**Comment by LukasNitsche** [comment]
Like this comment, if you are experiencing the same issue as described above.

**Comment by gsbgit** [comment]
The same problem here.
It worked like a charm last year. I hope it will be fixed very soon.

**Comment by Growianer** [comment]
Same here. Last Backup 20241104

**Comment by lavinir** [comment]
Issue has been found. See details here: #247
