### ISSUE TITLE
Problem with log

### ISSUE THREAD

**Issue by mrochette01** [lavinir/hassio-onedrive-backup#246]
Does this type of error mean anything to you?, Thank you

11/10/2024 15:42:12 [10] Info: Anonymous Telemetry Disabled
11/10/2024 15:42:12 [10] Info: Backup interval configured to every 24 hours
11/10/2024 15:42:12 [10] Info: Backups / Syncs will only run during these hours: 1,2,3
**11/10/2024 15:42:17 [14] Error: Error getting free space: Microsoft.Graph.Models.ODataErrors.ODataError: Access denied
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Drive.DriveRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetFreeSpaceInGB() in /src/Graph/GraphHelper.cs:line 243
11/10/2024 15:42:18 [11] Error: accessDenied: Access denied
11/10/2024 15:42:32 [11] Error: accessDenied: Access denied**
11/10/2024 15:47:18 [18] Error: Error getting free space: Microsoft.Graph.Models.ODataErrors.ODataError: Access denied
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Drive.DriveRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetFreeSpaceInGB() in /src/Graph/GraphHelper.cs:line 243
11/10/2024 15:47:19 [18] Error: accessDenied: Access denied
11/10/2024 15:47:50 [4] Info: Anonymous Telemetry Disabled
11/10/2024 15:47:50 [4] Info: Backup interval configured to every 24 hours
11/10/2024 15:47:50 [4] Info: Backups / Syncs will only run during these hours: 1,2,3
11/10/2024 15:47:53 [11] Error: Error getting free space: Microsoft.Graph.Models.ODataErrors.ODataError: Access denied
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Drive.DriveRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetFreeSpaceInGB() in /src/Graph/GraphHelper.cs:line 243
11/10/2024 15:47:54 [10] Error: accessDenied: Access denied
11/10/2024 15:52:54 [17] Error: Error getting free space: Microsoft.Graph.Models.ODataErrors.ODataError: Access denied
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Drive.DriveRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetFreeSpaceInGB() in /src/Graph/GraphHelper.cs:line 243
11/10/2024 15:52:55 [17] Error: accessDenied: Access denied

**Comment by mrochette01** [comment]
Do you have a solution ? Uninstall and install ?

**Comment by Growianer** [comment]
Same here. Last Backup 20241104

**Comment by lavinir** [comment]
Issue has been found. See details here: #247
