### ISSUE TITLE
OneDrive upload stopped working with v2.3.5

### ISSUE THREAD

**Issue by fbsdmon** [lavinir/hassio-onedrive-backup#251]
After updating to the latest version, and re-authenticating (successfully) to my OneDrive Personal account, OneDriveBackup doesn't want to upload backups to OneDrive :(

OneDrive Version: 2.3.5
Home Assistant Version
- Core: 2024.11.2
- Supervisor: 2024.11.2
- Operating System: 13.2
- Frontend: 20241106.2

Here is the verbose log output:

```
11/20/2024 16:51:41 [25] Verbose: Backup size to upload: 3.79GB
11/20/2024 16:51:41 [25] Info: Uploading hass_backup_2024-11-20-16-32 (11/20/2024 16:32:34)
11/20/2024 16:51:41 [25] Info: Fetching Local Backup (Slug:b2ab5a54)
11/20/2024 16:51:44 [24] Info: Backup (b2ab5a54) fetched successfully
11/20/2024 16:51:44 [24] Verbose: Backup Description: {"Slug":"b2ab5a54","BackupDate":"2024-11-20T16:32:34.889746+01:00","InstanceName":"raza","IsProtected":true,"Size":3794.5,"BackupType":"partial","Addons":[],"Folders":["addons/local","media","ssl"]}
11/20/2024 16:51:45 [22] Verbose: UploadSession Request: https://graph.microsoft.com/v1.0/drives/5BCE8EC684E50D69/items/5BCE8EC684E50D69%21101531:/hass_backup_2024-11-20-16-32.raza.tar:/createUploadSession. Body: {"item":{"description":"{\u0022Slug\u0022:\u0022b2ab5a54\u0022,\u0022BackupDate\u0022:\u00222024-11-20T16:32:34.889746\u002B01:00\u0022,\u0022InstanceName\u0022:\u0022raza\u0022,\u0022IsProtected\u0022:true,\u0022Size\u0022:3794.5,\u0022BackupType\u0022:\u0022partial\u0022,\u0022Addons\u0022:[],\u0022Folders\u0022:[\u0022addons/local\u0022,\u0022media\u0022,\u0022ssl\u0022]}"}}
11/20/2024 16:51:46 [22] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponseAsync(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 276
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 387
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : addon_5c53de3b_esphome_2024.2.0.raza.tar
11/20/2024 16:51:48 [25] Verbose: addon_5c53de3b_esphome_2024.2.0.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;4d1e42dc&quot;,&quot;BackupDate&quot;&#58;&quot;2024-02-29T19&#58;05&#58;13.814203+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;false,&quot;Size&quot;&#58;0.01,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : addon_5c53de3b_esphome_2024.3.0.raza.tar
11/20/2024 16:51:48 [25] Verbose: addon_5c53de3b_esphome_2024.3.0.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;6dff55ad&quot;,&quot;BackupDate&quot;&#58;&quot;2024-03-29T03&#58;36&#58;59.97502+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;false,&quot;Size&quot;&#58;0.01,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : addon_5c53de3b_esphome_2024.4.1.raza.tar
11/20/2024 16:51:48 [25] Verbose: addon_5c53de3b_esphome_2024.4.1.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;879d3568&quot;,&quot;BackupDate&quot;&#58;&quot;2024-04-30T09&#58;30&#58;20.75102+02&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;false,&quot;Size&quot;&#58;0.01,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : core_2023.12.3.raza.tar
11/20/2024 16:51:48 [25] Verbose: core_2023.12.3.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;5cfc2456&quot;,&quot;BackupDate&quot;&#58;&quot;2023-12-31T17&#58;39&#58;00.853307+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;false,&quot;Size&quot;&#58;167.52,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-01-31-01-22.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-01-31-01-22.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;60bfaa7c&quot;,&quot;BackupDate&quot;&#58;&quot;2024-01-31T01&#58;22&#58;48.707165+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;1053.83,&quot;BackupType&quot;&#58;&quot;full&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;share&quot;,&quot;addons/local&quot;,&quot;ssl&quot;,&quot;media&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-05-31-02-16.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-05-31-02-16.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;ae76cbad&quot;,&quot;BackupDate&quot;&#58;&quot;2024-05-31T02&#58;16&#58;07.852233+02&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;6722.23,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-06-30-02-58.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-06-30-02-58.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;7ebcc79a&quot;,&quot;BackupDate&quot;&#58;&quot;2024-06-30T02&#58;58&#58;44.83833+02&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;8496.85,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-07-31-04-16.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-07-31-04-16.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;38b8a4f3&quot;,&quot;BackupDate&quot;&#58;&quot;2024-07-31T04&#58;16&#58;47.865004+02&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;9497.57,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-08-31-05-15.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-08-31-05-15.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;f2aa1bc1&quot;,&quot;BackupDate&quot;&#58;&quot;2024-08-31T05&#58;15&#58;15.870249+02&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;5726.54,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-09-30-06-30.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-09-30-06-30.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;5043c583&quot;,&quot;BackupDate&quot;&#58;&quot;2024-09-30T06&#58;30&#58;59.61019+02&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;5657.14,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-10-31-01-36.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-10-31-01-36.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;a5de92ed&quot;,&quot;BackupDate&quot;&#58;&quot;2024-10-31T01&#58;36&#58;54.655708+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;4633.81,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-09-01-55.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-11-09-01-55.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;309cc10f&quot;,&quot;BackupDate&quot;&#58;&quot;2024-11-09T01&#58;55&#58;38.744286+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;4308.32,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-10-01-58.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-11-10-01-58.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;4d3bb6f6&quot;,&quot;BackupDate&quot;&#58;&quot;2024-11-10T01&#58;58&#58;51.731169+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;4328.52,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-11-02-00.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-11-11-02-00.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;2412f746&quot;,&quot;BackupDate&quot;&#58;&quot;2024-11-11T02&#58;00&#58;52.639826+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;4226.67,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-12-02-02.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-11-12-02-02.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;f1f7d17e&quot;,&quot;BackupDate&quot;&#58;&quot;2024-11-12T02&#58;02&#58;56.113826+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;4199.02,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-13-02-05.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-11-13-02-05.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;bcffb8d3&quot;,&quot;BackupDate&quot;&#58;&quot;2024-11-13T02&#58;05&#58;15.069496+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;4171.26,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-14-02-07.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-11-14-02-07.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;c6fb09d8&quot;,&quot;BackupDate&quot;&#58;&quot;2024-11-14T02&#58;07&#58;19.701974+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;4137.06,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-15-02-11.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-11-15-02-11.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;ac38e851&quot;,&quot;BackupDate&quot;&#58;&quot;2024-11-15T02&#58;11&#58;14.436119+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;4108.22,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-16-02-13.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-11-16-02-13.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;13515515&quot;,&quot;BackupDate&quot;&#58;&quot;2024-11-16T02&#58;13&#58;21.535199+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;4080.06,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
11/20/2024 16:51:48 [25] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-17-02-15.raza.tar
11/20/2024 16:51:48 [25] Verbose: hass_backup_2024-11-17-02-15.raza.tar Description: &#123;&quot;Slug&quot;&#58;&quot;13e73309&quot;,&quot;BackupDate&quot;&#58;&quot;2024-11-17T02&#58;15&#58;23.088767+01&#58;00&quot;,&quot;InstanceName&quot;&#58;&quot;raza&quot;,&quot;IsProtected&quot;&#58;true,&quot;Size&quot;&#58;4056.81,&quot;BackupType&quot;&#58;&quot;partial&quot;,&quot;Addons&quot;&#58;[],&quot;Folders&quot;&#58;[&quot;addons/local&quot;,&quot;media&quot;,&quot;ssl&quot;]&#125;
```

HELP :)

**Comment by KennethS2022** [comment]
I'm having the same problem. I updated to v2.3.5 and successfully re-authorised OneDrive access but backups remain local only.

**Comment by galgabor24** [comment]
Same here! After the last update (v2.3.5) my backups are local only :/ 
I tried to reinstall the add-on and re-authenticate again but it didn't fix the issue.

**Comment by THW712** [comment]
Thanks for your expertise and persistence, but regrettably I too am experiencing identical issues

**Comment by petepall** [comment]
I’m also not able to upload the backup.

the log is showing:

   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 387
11/20/2024 21:46:18 [32] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-17-01-17.tar
11/20/2024 21:46:18 [32] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-18-01-17.tar
11/20/2024 21:51:31 [40] Info: Backup complete
11/20/2024 21:51:31 [40] Info: Found 2 backups to upload.
11/20/2024 21:51:31 [40] Info: Uploading hass_backup_2024-11-20-21-35 (11/20/2024 21:35:55)
11/20/2024 21:51:31 [40] Info: Fetching Local Backup (Slug:331d20dd)
11/20/2024 21:54:39 [45] Info: Backup (331d20dd) fetched successfully
11/20/2024 21:54:49 [40] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponseAsync(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 209
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 387

**Comment by nickt444** [comment]
same as above after updating to 2.3.5.

11/21/2024 14:39:51 [27] Info: Uploading hass_backup_2024-11-15-11-53 (11/15/2024 11:53:46)
11/21/2024 14:39:51 [27] Info: Fetching Local Backup (Slug:a6000a48)
11/21/2024 14:39:53 [20] Info: Backup (a6000a48) fetched successfully
11/21/2024 14:39:57 [20] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponseAsync(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 276
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 425

and then lots of:
11/21/2024 14:40:15 [32] Warning: Unrecognized file found in backup folder : hass_backup_2024-09-19-15-23.tar

**Comment by voidoer** [comment]
Same issue for me:

11/21/2024 10:20:39 [19] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponseAsync(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 209
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 387
11/21/2024 10:20:40 [19] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-09-23-57.tar
11/21/2024 10:20:40 [19] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-11-00-01.tar
11/21/2024 10:20:40 [19] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-12-00-02.tar
11/21/2024 10:20:40 [19] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-13-00-03.tar
11/21/2024 10:20:40 [19] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-14-00-04.tar
11/21/2024 10:20:40 [19] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-15-00-05.tar
11/21/2024 10:20:40 [19] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-16-00-06.tar
11/21/2024 10:20:40 [19] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-17-00-07.tar
11/21/2024 10:20:40 [19] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-18-00-08.tar
11/21/2024 10:20:40 [19] Warning: Unrecognized file found in backup folder : hass_backup_2024-11-19-00-09.tar

**Comment by ibatten** [comment]
And for me, I am afraid: re-authenticated (to personal account) and now everyone seems to be local-only.  Existing backups are visible in Onedrive (of course) but new backups are not.  Log is mostly like this:

String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 276
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 425
11/21/2024 21:59:48 [19] Info: Uploading hass_backup_2024-11-06-16-36 (11/06/2024 16:36:32)
11/21/2024 21:59:48 [19] Info: Fetching Local Backup (Slug:88735812)
11/21/2024 21:59:51 [21] Info: Backup (88735812) fetched successfully
11/21/2024 21:59:53 [25] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponseAsync(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 276
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 425
11/21/2024 21:59:54 [25] Info: Uploading hass_backup_2024-11-02-16-11 (11/02/2024 16:11:07)
11/21/2024 21:59:54 [25] Info: Fetching Local Backup (Slug:7bbe39ae)
11/21/2024 21:59:57 [25] Info: Backup (7bbe39ae) fetched successfully
11/21/2024 22:00:00 [21] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponseAsync(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 276
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 425
11/21/2024 22:00:00 [21] Info: Uploading hass_backup_2024-10-31-15-58 (10/31/2024 15:58:02)
11/21/2024 22:00:00 [21] Info: Fetching Local Backup (Slug:399f83ca)

**Comment by Widgee9** [comment]
Same problem for me.

**Comment by Matzel92** [comment]
same problem here

**Comment by fratinaud** [comment]
same for me

**Comment by dercommander86** [comment]
same problem for me

**Comment by Jefke007** [comment]
Same problem here, anybody a update on the issue ?

**Comment by User-Frodolin** [comment]
I have the exact same problem!

**Comment by asgeirbakke** [comment]
I also have the same problem.

**Comment by GuidoJeuken-6512** [comment]
I have the same problem

**Comment by DavidCNZ2** [comment]
And for me. It also brought Hass on my RPi4 to its knees. Everything very slow and couldn't get a lot of panels to open until I finally got into Add-ons and stopped OneDrive Backup.

**Comment by sit-together** [comment]
Same problem - no upload to Onedrive anymore. There is a new folder in Onedrive named "Anwendungen/Graphs" that has been created with install of the AddOn, but no content. What about the former folder "hassio-onedrive-backup"?

**Comment by fdreckmann** [comment]
Same here

**Comment by KlausV66** [comment]
same here, any news?

**Comment by lavinir** [comment]
Please take a look at #209 and #247. I'm closing this to avoid having multiple threads but those issues are open.

I'm currently working on trying to isolate the reason for the upload failures people are experiencing but this existed before 2.3.5.

Consider adding the Preview Channel for the addon, I'm testing the fixes there first.
