### ISSUE TITLE
2.3.6 Unhandled exeption

### ISSUE THREAD

**Issue by Meckslo** [lavinir/hassio-onedrive-backup#260]
With the update to 2.3.5, I still had upload issues. With version 2.3.6, I'm experiencing a permissions problem. Does anyone know how to fix this?

```
11/26/2024 11:05:35 [4] Error: System.UnauthorizedAccessException: Access to the path '/config/onlineBackupsData/' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at hassio_onedrive_backup.Storage.LocalStorage.InitializeStorage(ConsoleLogger logger) in /src/Storage/LocalStorage.cs:line 46
   at hassio_onedrive_backup.Program.Main(String[] args) in /src/Program.cs:line 54
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/config/onlineBackupsData/' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at hassio_onedrive_backup.Storage.LocalStorage.InitializeStorage(ConsoleLogger logger) in /src/Storage/LocalStorage.cs:line 46
   at hassio_onedrive_backup.Program.Main(String[] args) in /src/Program.cs:line 54
   at hassio_onedrive_backup.Program.<Main>(String[] args)
```

**Comment by lavinir** [comment]
I actually didn't intend for this to be the save location. But permissions wise this is requested in the addon config. Did you modify any permissions on your config dir? Could you try manually creating that folder and see if it's able to use it ?

**Comment by IamSam-O** [comment]
This issue started occurring for me after 12.1 core upgrade. I have attempted to make directory "onlineBackupsData" in /config. There is no improvement or change after starting the addon again.

**Comment by IamSam-O** [comment]
[1] Info: No new settings file. Attempting to restore from legacy configuration
12/16/2024 21:47:50 [11] Error: System.UnauthorizedAccessException: Access to the path '/config/onlineBackupsData/' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at hassio_onedrive_backup.Storage.LocalStorage.InitializeStorage(ConsoleLogger logger) in /src/Storage/LocalStorage.cs:line 46
   at hassio_onedrive_backup.Program.Main(String[] args) in /src/Program.cs:line 54

**Comment by lavinir** [comment]
Strange. Wonder why this would happen to only some installations. Anyway, I want to change that location to be under the addon config folder, will have this in an upcoming update.

**Comment by IamSam-O** [comment]
I have found a work around that will allow the addon to launch without errors. All though its not permanent, and it needs more testing to determine if the addons full functionality will work.

**Comment by IamSam-O** [comment]
1. Utilizing the portatiner addon locate and open the container for OneDrive Backup. 
2. Under Actions Select Duplicate/Edit 
![image](https://github.com/user-attachments/assets/46370b87-d649-44b5-b882-24ad5e294254)
3. Selected Volumes under Advanced container settings
4. Delete the Container labeled "/addons"
![image](https://github.com/user-attachments/assets/8c12c00c-fac0-4d9c-b9d1-afdce0aa8f54)
6. Deploy the container 
![image](https://github.com/user-attachments/assets/a867d7b2-c20c-44b7-bfa2-3cc429e8ec91)
7. Open Addon

**Comment by IamSam-O** [comment]
Addon appears to be fully working after applying work around.
![image](https://github.com/user-attachments/assets/2e36a8f5-f7e2-4d89-b0fd-bf2f699d679f)

**Comment by lavinir** [comment]
I'm not sure why this would be related. In terms of side effects though, the only one which is probably not impactful to most users is you wouldn't be able to sync that folder using the File Sync capability..

**Comment by fghpdf** [comment]
Hi I met the same issue, and I reinstalled it but the issue still exists.

There is the log:

```
Info: No new settings file. Attempting to restore from legacy configuration
02/12/2025 21:36:28 [4] Error: System.UnauthorizedAccessException: Access to the path '/config/onlineBackupsData/' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at hassio_onedrive_backup.Storage.LocalStorage.InitializeStorage(ConsoleLogger logger) in /src/Storage/LocalStorage.cs:line 47
   at hassio_onedrive_backup.Program.Main(String[] args) in /src/Program.cs:line 54
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/config/onlineBackupsData/' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at hassio_onedrive_backup.Storage.LocalStorage.InitializeStorage(ConsoleLogger logger) in /src/Storage/LocalStorage.cs:line 47
   at hassio_onedrive_backup.Program.Main(String[] args) in /src/Program.cs:line 54
   at hassio_onedrive_backup.Program.<Main>(String[] args)

```
