### ISSUE TITLE
Upload not possible

### ISSUE THREAD

**Issue by fdreckmann** [lavinir/hassio-onedrive-backup#261]
> 11/26/2024 12:42:05 [10] Info: Anonymous Telemetry Disabled
11/26/2024 12:42:05 [10] Info: Backup interval configured to every 24 hours
11/26/2024 12:42:07 [11] Info: To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code MTYXJDY4 to authenticate.
11/26/2024 12:42:47 [14] Error: invalidRequest: Invalid request
11/26/2024 12:43:38 [14] Info: Creating new backup
11/26/2024 12:43:38 [14] Info: Starting full local backup
11/26/2024 12:45:17 [18] Info: Backup complete
11/26/2024 12:45:42 [23] Info: Uploading hass_backup_2024-11-26-12-43 (11/26/2024 12:43:38)
11/26/2024 12:45:42 [23] Info: Fetching Local Backup (Slug:dab6a954)
11/26/2024 12:46:04 [18] Info: Backup (dab6a954) fetched successfully
11/26/2024 12:46:13 [18] Error: Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponseAsync(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Special.Item.DriveItemItemRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 208
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 394
11/26/2024 12:46:14 [25] Error: invalidRequest: Invalid request

Version: 2.3.6

**Comment by lavinir** [comment]
This is happening on 2.3.6 ?
Could you share the verbose logs please ?

**Comment by fdreckmann** [comment]
Of course, Here the Log.
I have complete new Install, authentication and Backup in this Log.
[logs-2.txt](https://github.com/user-attachments/files/18052130/logs-2.txt)

**Comment by lavinir** [comment]
There are some error logs there I have no idea where they're coming from. 
Could you share some more details about your setup ? (How you're running Home Assistant and the addon?)

Could you try to set the logging level to Verbose and send the logs again?

**Comment by lavinir** [comment]
Could you please share the verbose logs ?

**Comment by fdreckmann** [comment]
Maybe a stupid question, where i get the logs?

lavinir ***@***.***> schrieb am Mo., 9. Dez. 2024, 14:39:

**Comment by lavinir** [comment]
Go to the addon page (Settings -> Addons). You will have a Log tab on the right.
![image](https://github.com/user-attachments/assets/1d794b51-3730-4605-b280-b27795ff6197)

**Comment by fdreckmann** [comment]
I've attached the exact log in the first post.

lavinir ***@***.***> schrieb am Mo., 9. Dez. 2024, 19:31:

**Comment by lavinir** [comment]
You need to change the log level in the settings tab inside the Addon UI to Verbose to see the additional logs..

**Comment by fdreckmann** [comment]
Ah ok, Here the Log :)
[logs-3.txt](https://github.com/user-attachments/files/18076812/logs-3.txt)

**Comment by lavinir** [comment]
Are you signed in? The logs are showing you aren't authenticated with OneDrive?
Could you confirm if you successfully logged in / are using a Microsoft Personal account ?

**Comment by fdreckmann** [comment]
Of course, i used Personal Account authentication is Good says Microsoft. I
can send you a picture if you need.

lavinir ***@***.***> schrieb am Di., 10. Dez. 2024, 13:33:

**Comment by lavinir** [comment]
After signing in you're still getting the log telling you to sign in ?
This is a personal (non business) account right ?

Has this ever worked in the past ? Could you try uninstalling completely and see what happens with a clean install of the addon?

**Comment by fdreckmann** [comment]
I have 10 times Reinstall xd. In the past it Works great. I used a normal
Personal Account (but Family Plan)

lavinir ***@***.***> schrieb am Di., 10. Dez. 2024, 14:47:

**Comment by lavinir** [comment]
Could there still be some artifacts from an older version on your system? The pop up with the changelog is showing 2.3.5 instead of 2.3.6

Do you have another account you can try on this device to see if there's a change? Or another Home Assistant installation to try the current account ?

**Comment by jaaphoenderdos** [comment]
Hi, I am experiencing exactly the same problem. Also the message that I am on version 2.3.5 while 2.3.6 is installed.

**Comment by lavinir** [comment]
Version 2.3.8 is out in the preview channel, contains some fixes and additional logging.
Could you please install that and update on if there's a change (if not there should be more info on the error in the logs)

**Comment by jaaphoenderdos** [comment]
Installed 2.3.8/. No luck. See verbose logs

[6449d918_hassio_onedrive_backup_2024-12-16T13-01-56.825Z.log](https://github.com/user-attachments/files/18150345/6449d918_hassio_onedrive_backup_2024-12-16T13-01-56.825Z.log)

**Comment by lavinir** [comment]
Those things are probably related. It's failing getting the 'App Folder' from onedrive, which should be the **hassio-onedrive-backup**

Could you try removing permissions from the app from your microsoft account completely and re-installing the addon (to clear any auth cache).

Also, this is a standard personal onedrive account ?

**Comment by jaaphoenderdos** [comment]
Tried that before, and will try again.

Standard personal account with family subscription.

**Comment by lavinir** [comment]
Tried to do a little digging. There are other people reporting this issue with the OneDrive App Folder. I found an issue opened in their docs as well [here](https://github.com/OneDrive/onedrive-api-docs/issues/1866)

To be honest, until it's clear why this is happening I'm not currently sure what can be done from my end (unless I drop the app folder and just go for full read write permissions on OneDrive)
