### ISSUE TITLE
Exception: The process cannot access the file

### ISSUE THREAD

**Issue by szczukot** [lavinir/hassio-onedrive-backup#262]
ver 2.3.6

11/26/2024 08:08:07 [40] Info: Creating new backup
11/26/2024 08:08:07 [40] Info: Starting full local backup
11/26/2024 08:08:21 [40] Info: Backup complete
11/26/2024 08:08:50 [42] Info: Uploading hass_backup_2024-11-26-08-08 (11/26/2024 08:08:07)
11/26/2024 08:08:50 [42] Info: Fetching Local Backup (Slug:90021999)
11/26/2024 08:08:51 [74] Info: Backup (90021999) fetched successfully
11/26/2024 08:08:53 [42] Info: Starting file upload. (Size:156026880 bytes. Attempt: 1/3)
11/26/2024 08:09:13 [74] Info: Found 1 backups to upload.
11/26/2024 08:09:13 [69] Info: Uploading hass_backup_2024-11-26-08-08 (11/26/2024 08:08:07)
11/26/2024 08:09:13 [69] Info: Fetching Local Backup (Slug:90021999)
11/26/2024 08:09:13 [59] Error: Error uploading backup: System.IO.IOException: The process cannot access the file '/tmp/90021999.tar' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Create(String path)
   at hassio_onedrive_backup.Hass.HassioClient.DownloadBackupAsync(String backupSlug) in /src/Hass/HassioClient.cs:line 220
   at hassio_onedrive_backup.Hass.HassioClient.DownloadBackupAsync(String backupSlug) in /src/Hass/HassioClient.cs:line 223
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 393

**Comment by ovanpeve** [comment]
Have exactly the same after update.

**Comment by lavinir** [comment]
Does this keep happening. I don't have the earlier logs but based on what @szczukot shared, it looks like 2 concurrent tasks are trying to upload the backup (which shouldn't happen) - Did this just happen live after upgrade ?

**Comment by szczukot** [comment]
So far it hasn't happened to me again
