### ISSUE TITLE
System.IO.IOException: Permission denied

### ISSUE THREAD

**Issue by IamSam-O** [lavinir/hassio-onedrive-backup#273]
The add-on is unable to start due to System.IO.IOException: Permission denied. I have attempted to delete the docker image and volumes, followed by a full reboot. The issue persists after reinstalling the add-on.

**Comment by IamSam-O** [comment]
[1] Info: No new settings file. Attempting to restore from legacy configuration
12/13/2024 11:26:35 [4] Error: System.UnauthorizedAccessException: Access to the path '/config/onlineBackupsData/' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at hassio_onedrive_backup.Storage.LocalStorage.InitializeStorage(ConsoleLogger logger) in /src/Storage/LocalStorage.cs:line 46
   at hassio_onedrive_backup.Program.Main(String[] args) in /src/Program.cs:line 54
 [1] Info: No new settings file. Attempting to restore from legacy configuration
12/13/2024 11:34:05 [10] Error: System.UnauthorizedAccessException: Access to the path '/config/onlineBackupsData/' is denied.

**Comment by lavinir** [comment]
Someone else reported this as well. Let's try to consolidate into one issue. Please look at #260 
Let me know if creating the folder manually works.
