### ISSUE TITLE
Endless Uploads after Error

### ISSUE THREAD

**Issue by camsaway** [lavinir/hassio-onedrive-backup#285]
Hi,

I see there are a number of issues logged that sound similar but not exactly the same. At 2216 last night I experience the below error and since then the add-on has been sending continuously - it appears that uploads are not working and it's constantly retrying.

`
12/27/2024 22:12:23 [34] Error: Failed getting Drive Id. Microsoft.Graph.Models.ODataErrors.ODataError: General exception while processing
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponseAsync(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.DrivesRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetDriveIdFromAppFolder() in /src/Graph/GraphHelper.cs:line 383
12/27/2024 22:12:23 [34] Error: generalException: General exception while processing. Microsoft.Graph.Models.ODataErrors.ODataError: General exception while processing
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponseAsync(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.DrivesRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetDriveIdFromAppFolder() in /src/Graph/GraphHelper.cs:line 383
   at hassio_onedrive_backup.Graph.GraphHelper.GetItemsInAppFolderAsync(String subPath) in /src/Graph/GraphHelper.cs:line 203
`

**Comment by brzozow** [comment]
I have the same issue.

**Comment by camsaway** [comment]
I have done the following and it has worked for me.

Stop the add-on
Delete all backups on HASS
Delete all backups on OneDrive
Reboot the HASS server

All these steps might not be necessary but just restarting HASS didn't work so I tried fully resetting the add-on.

After this the add-on ran a backup which it uploaded and I wait to see how the next one goes.

**Comment by lavinir** [comment]
Thanks @camsaway glad you got it working . There may be some residual issues with the migration to the new App Auth system (not sure why it isn't consistent across users) but deleting backups should not be related to this at all and I wouldn't encourage you to do this :)

@brzozow, are you still experiencing this issue ?
