### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by AFumi39** [lavinir/hassio-onedrive-backup#41]
From yesterday I've some problems with this component. I though that is was related with the problems with all MS services, so I just stopped the component until today. I updated to 1.41 and started again (enabling the new feature that sync also other backups). It uploaded the first small backup (generated from component update) and then is stuck with this other backup that's bigger with this error (that occurs everytime it try to upload this file):
```
01/26/2023 10:31:28 [22] Info: Uploading Partial Backup 2023-01-26 02:30:00 (01/26/2023 02:30:00)
01/26/2023 10:31:28 [22] Info: Fetching Local Backup (Slug:4e73a180)
01/26/2023 10:32:13 [22] Info: Backup (4e73a180) fetched successfully
01/26/2023 10:32:14 [22] Error: Unexpected error. Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: BadRequest
Message: Multiple action overloads were found with the same binding parameter for 'microsoft.graph.createUploadSession'.
Inner error:
	AdditionalData:
	date: 2023-01-26T09:32:14
	request-id: 5d84ffdd-7741-45a1-9120-99a4bab54df0
	client-request-id: 5d84ffdd-7741-45a1-9120-99a4bab54df0
ClientRequestId: 5d84ffdd-7741-45a1-9120-99a4bab54df0
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, String destinationFileName, Action`1 progressCallback, Boolean flatten, Boolean omitDescription) in /src/Graph/GraphHelper.cs:line 129
   at hassio_onedrive_backup.Hass.BackupManager.PerformBackupsAsync() in /src/Hass/BackupManager.cs:line 114
   at hassio_onedrive_backup.Program.Main(String[] args) in /src/Program.cs:line 89
01/26/2023 10:32:14 [22] Info: Backup Interval Completed.
```

**Comment by lavinir** [comment]
Could you clarify - the failed uploads are for File Syncs not the backups right ? 
This error is coming from the official MS library. I saw a reference to this happening when there are "special characters" in the file name. Could you share the file name being uploaded when this error occurs ?

**Comment by AFumi39** [comment]
It's a backup file of my HA instance, generated via script, that's have nothing particular, as I can see... maybe it's the colon character in the file name?
The file name's "Partial Backup 2023-01-26 02:30:00.tar"

**Comment by lavinir** [comment]
it is definitely the colon. Would you please try without it and verify.

**Comment by AFumi39** [comment]
I'll try to delete and make new one without the colon (I can't rename it from HA interface, and in file system the name is a sort of checksum and not the one showed/used by UI and your component) and I let you know.

Thanks

**Comment by AFumi39** [comment]
Confirmed that it now works! ^^
