### ISSUE TITLE
Unexpected error. Status Code: BadRequest

### ISSUE THREAD

**Issue by cbloy** [lavinir/hassio-onedrive-backup#48]
Super excited to find this add-on.  I can finally be able to use my onedrive space for good! 

Appreciate any help! 

I'm running on proxmox:
Home Assistant 2023.2.2
Supervisor 2023.01.1
Operating System 9.5

After installing, it detects the existing local backups and I get the following in the logs:

02/15/2023 19:30:53 [5] Info: Backup interval configured to every 72 hours
02/15/2023 19:30:53 [5] Warning: Token cache is empty
02/15/2023 19:30:55 [10] Info: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code xxxxxxxxx to authenticate.
02/15/2023 19:32:16 [10] Info: Checking backups
02/15/2023 19:32:16 [10] Info: Retrieving existing local backups...
02/15/2023 19:32:16 [10] Info: Retrieving existing online backups...
02/15/2023 19:32:17 [9] Info: Last local backup Date: 02/15/2023 09:39:24
02/15/2023 19:32:17 [9] Info: Last online backup Date: None
02/15/2023 19:32:17 [9] Info: Found 4 backups to upload.
02/15/2023 19:32:17 [7] Info: Uploading Full Backup 2023-02-15 09:39:24 (02/15/2023 09:39:24)
02/15/2023 19:32:17 [7] Info: Fetching Local Backup (Slug:6b5574b5)
02/15/2023 19:33:30 [19] Info: Backup (6b5574b5) fetched successfully
02/15/2023 19:34:05 [13] Error: Unexpected error. Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: BadRequest
Message: Multiple action overloads were found with the same binding parameter for 'microsoft.graph.createUploadSession'.
Inner error:
	AdditionalData:
	date: 2023-02-16T01:34:05
	request-id: 12d2cdf3-b69a-43de-ba3d-6331fa65dab8
	client-request-id: 12d2cdf3-b69a-43de-ba3d-6331fa65dab8
ClientRequestId: 12d2cdf3-b69a-43de-ba3d-6331fa65dab8
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, String destinationFileName, Action`1 progressCallback, Boolean flatten, Boolean omitDescription) in /src/Graph/GraphHelper.cs:line 129
   at hassio_onedrive_backup.Hass.BackupManager.PerformBackupsAsync() in /src/Hass/BackupManager.cs:line 114
02/15/2023 19:34:05 [13] Info: Backup Interval Completed.
   at hassio_onedrive_backup.Program.Main(String[] args) in /src/Program.cs:line 89
02/15/2023 19:39:05 [25] Info: Checking backups
02/15/2023 19:39:05 [25] Info: Retrieving existing local backups...
02/15/2023 19:39:05 [25] Info: Retrieving existing online backups...
02/15/2023 19:39:06 [25] Info: Last local backup Date: 02/15/2023 09:39:24

**Comment by lavinir** [comment]
Yes I agree this error is not very clear. Look at this issue: #41 .
This is likely unsupported (by OneDrive) path characters in your file name.

**Comment by cbloy** [comment]
That is it, I deleted my existing backups before I installed the addon and it is working!  Thank you!
