### ISSUE TITLE
Cannot authenticate Onedrive for Business and not possible to retry

### ISSUE THREAD

**Issue by gwindtcareyn** [lavinir/hassio-onedrive-backup#5]
I have tried to authenticate Onedrive for Business, with correct credentials and was able to grand permissions. But it is reporting access denied. There is also no option to reset the authentication token and I don't know where it is stored.

10/27/2022 19:21:41 Info: Backup interval configured to every 72 hours
10/27/2022 19:21:41 Info: Checking backups
10/27/2022 19:21:42 Error: Unexpected error. Status Code: Forbidden
Microsoft.Graph.ServiceException: Code: accessDenied
Message: Access denied
Inner error:
	AdditionalData:
	date: 2022-10-27T19:21:42
	request-id: 051c0692-1797-47c2-9217-9075e93448f7
	client-request-id: 051c0692-1797-47c2-9217-9075e93448f7
ClientRequestId: 051c0692-1797-47c2-9217-9075e93448f7
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.DriveItemChildrenCollectionRequest.GetAsync(CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetItemsInAppFolderAsync() in /src/Graph/GraphHelper.cs:line 57
   at hassio_onedrive_backup.Hass.BackupManager.GetOnlineBackupsAsync(String backupName) in /src/Hass/BackupManager.cs:line 193
   at hassio_onedrive_backup.Hass.BackupManager.UpdateHassEntity() in /src/Hass/BackupManager.cs:line 150
   at hassio_onedrive_backup.Hass.BackupManager.PerformBackupsAsync() in /src/Hass/BackupManager.cs:line 26
   at hassio_onedrive_backup.Program.Main(String[] args) in /src/Program.cs:line 41

**Comment by lavinir** [comment]
Hi, 

Sorry, OneDrive for business is not supported, you will need to use a personal account. 
I Wouldn't have thought it would let you login with that account but I guess that's why it goes into a loop. 
If you want to try again with a personal account you could uninstall the addon and reinstall it, it would then let you re-authenticate with another account.

**Comment by gwindtcareyn** [comment]
Too bad, I don't have Onedrive personal and I don't want it.
I guess its not for me then.

**Comment by gomble** [comment]
Would be very nice if you support onedrive business.
This Addon would be insane 👍

**Comment by lavinir** [comment]
There is a technical limitation currently. the App Folder permissions is not supported in OneDrive for business and the alternative would be getting access to all Files and Folders which I'd rather not go down that path.

Will keep this in the backlog.
