### ISSUE TITLE
Post 2.0 Backup Fails With Errors

### ISSUE THREAD

**Issue by ziptbm** [lavinir/hassio-onedrive-backup#58]
Upgraded to 2.0 and re-authenticated.  Following that, I had it take another local update and attempt to upload and ran into the following errors.  It appears to be the same with each attempt.

```
03/21/2023 11:28:13 [21] Info: Uploading Automated Backup 2023-03-21 (03/21/2023 01:00:00)
03/21/2023 11:28:13 [21] Info: Fetching Local Backup (Slug:2c86e01c)
03/21/2023 11:28:55 [6] Info: Backup (2c86e01c) fetched successfully
03/21/2023 11:28:56 [6] Info: Starting file upload. (Size:6313338880 bytes. Attempt: 1/3)
03/21/2023 11:28:57 [6] Error: Error uploading: Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: generalException
Message: Unexpected exception returned from the service.
   at Microsoft.Graph.SimpleHttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.UploadSliceRequest`1.SendRequestAsync(Stream stream, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.UploadSliceRequest`1.PutAsync(Stream stream, CancellationToken cancellationToken)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadSliceAsync(UploadSliceRequest`1 uploadSliceRequest, ICollection`1 exceptionTrackingList)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, String destinationFileName, Action`1 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 179
03/21/2023 11:28:58 [18] Info: Uploading Automated Backup 2023-03-20 (03/20/2023 01:00:00)
03/21/2023 11:28:58 [18] Info: Fetching Local Backup (Slug:f7113fb4)
03/21/2023 11:29:39 [24] Info: Backup (f7113fb4) fetched successfully
03/21/2023 11:29:40 [24] Info: Starting file upload. (Size:6214717440 bytes. Attempt: 1/3)
03/21/2023 11:29:41 [24] Error: Error uploading: Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: generalException
Message: Unexpected exception returned from the service.
   at Microsoft.Graph.SimpleHttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.UploadSliceRequest`1.SendRequestAsync(Stream stream, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.UploadSliceRequest`1.PutAsync(Stream stream, CancellationToken cancellationToken)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadSliceAsync(UploadSliceRequest`1 uploadSliceRequest, ICollection`1 exceptionTrackingList)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, String destinationFileName, Action`1 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 179
03/21/2023 11:32:01 [23] Info: Uploading Automated Backup 2023-03-21 (03/21/2023 01:00:00)
03/21/2023 11:32:01 [23] Info: Fetching Local Backup (Slug:2c86e01c)
03/21/2023 11:32:42 [21] Info: Backup (2c86e01c) fetched successfully
03/21/2023 11:32:45 [16] Info: Starting file upload. (Size:6313338880 bytes. Attempt: 1/3)
03/21/2023 11:32:46 [23] Error: Error uploading: Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: generalException
Message: Unexpected exception returned from the service.
   at Microsoft.Graph.SimpleHttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.UploadSliceRequest`1.SendRequestAsync(Stream stream, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.UploadSliceRequest`1.PutAsync(Stream stream, CancellationToken cancellationToken)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadSliceAsync(UploadSliceRequest`1 uploadSliceRequest, ICollection`1 exceptionTrackingList)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, String destinationFileName, Action`1 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 179
```

**Comment by ziptbm** [comment]
> This is new to 2.0? Why did you need to re authenticate? Did you uninstall the previous version first?
> 
> Does this happen with all backups?

I stopped using it back in Nov/Dec due to errors at that time...I don't recall exactly what it was, but the lack of ability to force an upload was one of the reasons I reverted to another system.   After seeing the 2.0 update, I upgraded, which forced me to re-authenticate since I hadn't used it over 100 days.  I did NOT uninstall the previous version first.  Should I try that?

Right now it's showing the backups from 100 days ago, but it doesn't appear to work when I "trigger backup" or ask to upload another backup I took 11 hours ago.

**Comment by lavinir** [comment]
If your config is so old maybe it's worth trying a clean install jsut in case. 

Also something is strange with your logs with the generated backup name.
Could you try to remove the configured name you have (Automated Backup?) and use just "hass"?

If you still experience an issue appreciate if you can share your config with the full logs.

**Comment by lavinir** [comment]
The added functionality allows both on demand uploads as well as on demand backup creation.

I'd like to see what happens for a backup created by the addon as well. You can trigger a backup from the web ui.

**Comment by ziptbm** [comment]
OK, new install.  I'm having it right now ignore all other local backups (e.g. the ones labeled "automated backup..."), and asked it to trigger a backup.  It says complete, but literally nothing was backed up and uploaded.  Look at the time between starting and complete.  My backups take 6GB at least, so that's clearly not right.  The only backups that show in OneDrive now are 2 from Nov and 1 partial from yesterday.

```
03/21/2023 12:18:50 [6] Info: Checking backups
03/21/2023 12:18:50 [6] Info: Backup Interval Completed.
03/21/2023 12:18:50 [6] Info: Retrieving existing local backups...
03/21/2023 12:18:50 [6] Info: Retrieving existing online backups...
03/21/2023 12:18:50 [6] Info: Last local backup Date: None
03/21/2023 12:18:50 [6] Info: Last online backup Date: 03/20/2023 17:01:21
03/21/2023 12:18:50 [6] Info: Online backups synced. No upload required
03/21/2023 12:19:25 [15] Info: Creating new backup
03/21/2023 12:19:25 [15] Info: Starting full local backup
03/21/2023 12:19:25 [3] Info: Backup complete
03/21/2023 12:20:27 [17] Info: Creating new backup
03/21/2023 12:20:27 [17] Info: Starting full local backup
03/21/2023 12:20:27 [18] Info: Backup complete
```

When I re-enable monitoring all local backups, I get the following :
```
03/21/2023 12:23:22 [6] Info: Backup interval configured to every 72 hours
03/21/2023 12:23:23 [10] Info: Checking backups
03/21/2023 12:23:23 [10] Info: Backup Interval Completed.
03/21/2023 12:23:23 [6] Info: Retrieving existing local backups...
03/21/2023 12:23:23 [6] Info: Retrieving existing online backups...
03/21/2023 12:23:23 [6] Info: Last local backup Date: 03/21/2023 11:11:05
03/21/2023 12:23:23 [6] Info: Last online backup Date: 03/20/2023 17:01:21
03/21/2023 12:23:23 [6] Info: Found 2 backups to upload.
03/21/2023 12:23:23 [6] Info: Uploading hass_backup_2023-03-21-11-11 (03/21/2023 11:11:05)
03/21/2023 12:23:23 [6] Info: Fetching Local Backup (Slug:f76ad403)
03/21/2023 12:24:56 [10] Info: Backup (f76ad403) fetched successfully
03/21/2023 12:24:56 [10] Info: Starting file upload. (Size:12208855040 bytes. Attempt: 1/3)
03/21/2023 12:24:57 [17] Error: Error uploading: Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: generalException
Message: Unexpected exception returned from the service.
   at Microsoft.Graph.SimpleHttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.UploadSliceRequest`1.SendRequestAsync(Stream stream, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.UploadSliceRequest`1.PutAsync(Stream stream, CancellationToken cancellationToken)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadSliceAsync(UploadSliceRequest`1 uploadSliceRequest, ICollection`1 exceptionTrackingList)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, String destinationFileName, Action`1 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 179
03/21/2023 12:24:58 [17] Info: Uploading Automated Backup 2023-03-21 (03/21/2023 01:00:00)
03/21/2023 12:24:58 [17] Info: Fetching Local Backup (Slug:2c86e01c)
03/21/2023 12:26:11 [14] Info: Backup (2c86e01c) fetched successfully
03/21/2023 12:26:11 [14] Info: Starting file upload. (Size:6313338880 bytes. Attempt: 1/3)
03/21/2023 12:26:12 [8] Error: Error uploading: Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: generalException
Message: Unexpected exception returned from the service.
   at Microsoft.Graph.SimpleHttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.UploadSliceRequest`1.SendRequestAsync(Stream stream, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.UploadSliceRequest`1.PutAsync(Stream stream, CancellationToken cancellationToken)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadSliceAsync(UploadSliceRequest`1 uploadSliceRequest, ICollection`1 exceptionTrackingList)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, String destinationFileName, Action`1 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 179
```


Does this add-on cache the backup and double it?  I'm now seeing an 11-12GB backup that was created an hour ago, and I believe it was by this add-on.  here's what I see in another backup tool, that shows what each component of the backup is consuming in space.
<img width="446" alt="image" src="https://user-images.githubusercontent.com/46136563/226676070-d6dfb046-a0d2-456a-8510-b193de61c8c0.png">

**Comment by lavinir** [comment]
Also have another suspicion,
Do you have a large number of add-ons installed included in the backups?

**Comment by lavinir** [comment]
Thank you for the info.
The addon uses the supervisor api to interact with the backups. 
So before sending to onedrive the backup is locally cached as it is essentially "downloaded" from home assistant as opposed to accessing the file system directly. 
The temporary file should be removed after upload, or upload failure (I will check there is no edge case causing any to remain) 

With regards to the backup completing immediately you are right, but as this is also done with the supervisor api you should see logs in home assistant under supervisor showing a request for creating a backup and seeing what happened with it. 

Finally, the lingering issue with the upload failure, I have an idea I need to follow up on that is something new to 2.0. Will update later

**Comment by lavinir** [comment]
Ok I found the issue, (it is related to the number of addons) will hopefully get a fix / workaround for this later. 
Thank you for all the information;

**Comment by lavinir** [comment]
Pushed 2.01 - Let me know if this resolves your upload issue. @ziptbm

**Comment by ziptbm** [comment]
After changing to 90, restarting add-on, and trying to trigger a backup, I get this:

```
03/22/2023 10:32:54 [10] Info: Backup interval configured to every 72 hours
03/22/2023 10:32:55 [8] Info: Checking backups
03/22/2023 10:32:55 [8] Info: Backup Interval Completed.
03/22/2023 10:32:55 [10] Info: Retrieving existing local backups...
03/22/2023 10:32:55 [10] Info: Retrieving existing online backups...
03/22/2023 10:32:56 [13] Info: Last local backup Date: None
03/22/2023 10:32:56 [13] Info: Last online backup Date: 03/20/2023 17:01:21
03/22/2023 10:32:56 [13] Info: Online backups synced. No upload required
03/22/2023 10:34:12 [14] Info: Creating new backup
03/22/2023 10:34:12 [14] Info: Starting full local backup
03/22/2023 10:34:12 [15] Info: Backup complete
03/22/2023 10:34:44 [15] Info: Creating new backup
03/22/2023 10:34:44 [15] Info: Starting full local backup
03/22/2023 10:34:44 [14] Info: Backup complete
```

So, it still is not working for me unfortunately.

**Comment by lavinir** [comment]
@ziptbm , 
Glad upload is working. 
I've reproduced the issue where the backup seems to complete immediately. This happens when Home assistant already has a backup in progress. 
You mentioned your backups are very large, I imagine they take a while to complete. During that time it is not possible to trigger another backup.
I will see if I have a better way to detect this so that the logs are more accurate as to what is happening.

Otherwise do you still have any issues ?

**Comment by ziptbm** [comment]
@lavinir it seems like it create the backup automatically and uploaded without issue, so it's looking good!

Note I'm running this in parallel with a Google Drive Backup add-on (I'm paranoid), but would prefer OneDrive sine I have so much more space there.  To avoid any issues, I'm having each add-on ignore other backups on the system.   

Now, I just need to figure out how to reduce my backup size...  Thanks again for this!
