### ISSUE TITLE
Files not uploadet

### ISSUE THREAD

**Issue by senjo2** [lavinir/hassio-onedrive-backup#80]
Hello,
at first: Thanks for this Add-on!!!

In my case some backup-files will not be uploadet.
In the web UI is a UPLOAD button, but it will not work.
Other backup-files where uploadet.
![grafik](https://user-images.githubusercontent.com/122204680/231248562-a047ec03-0e56-4127-a5d8-e276eb3a7190.png)

The LOG marks an error:

04/11/2023 20:12:11 [56] Info: Found 8 backups to upload.
04/11/2023 20:12:11 [56] Info: Uploading Manuelles_Backup_2023-04-11 19:37 (04/11/2023 19:37:40)
04/11/2023 20:12:11 [56] Info: Fetching Local Backup (Slug:ba859795)
04/11/2023 20:12:12 [56] Info: Backup (ba859795) fetched successfully
04/11/2023 20:12:13 [56] Error: Error uploading backup: Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: BadRequest
Message: Multiple action overloads were found with the same binding parameter for 'microsoft.graph.createUploadSession'.
Inner error:
	AdditionalData:
	date: 2023-04-11T18:12:13
	request-id: 06ae8f18-89cf-4206-82aa-d79fb4a18d07
	client-request-id: 06ae8f18-89cf-4206-82aa-d79fb4a18d07
ClientRequestId: 06ae8f18-89cf-4206-82aa-d79fb4a18d07
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 209
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup backup, Action`2 progressCallback, Boolean updateHassEntityState) in /src/Hass/BackupManager.cs:line 276
04/11/2023 20:12:13 [56] Info: Uploading hass Full - 2023-04-11 00:00 os-version: 2023.4.2 (04/11/2023 00:00:20)
04/11/2023 20:12:13 [56] Info: Fetching Local Backup (Slug:d0ad847d)
04/11/2023 20:12:14 [56] Info: Backup (d0ad847d) fetched successfully
04/11/2023 20:12:14 [56] Error: Error uploading backup: Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: BadRequest
Message: Multiple action overloads were found with the same binding parameter for 'microsoft.graph.createUploadSession'.
Inner error:
	AdditionalData:
	date: 2023-04-11T18:12:14
	request-id: 0e522b0d-157a-4bf7-87d6-5506a75ea145
	client-request-id: 0e522b0d-157a-4bf7-87d6-5506a75ea145
ClientRequestId: 0e522b0d-157a-4bf7-87d6-5506a75ea145
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, TransferSpeedHelper transferSpeedHelper, String destinationFileName, Action`2 progressCallback, Boolean flatten, String description) in /src/Graph/GraphHelper.cs:line 209
   at hassio_onedrive_backup.Hass.BackupManager.UploadLocalBackupToOneDrive(Backup bac

It would be nice, if you have a solution.

Regards, Joachim

**Comment by lavinir** [comment]
Hi,

This happens when there are unsupported (by OneDrive) characters in the filename.
See #48

**Comment by lavinir** [comment]
@senjo2 - Do you still have any issues ?

**Comment by lavinir** [comment]
Closing..
