### ISSUE TITLE
Stoped in ..Initializing

### ISSUE THREAD

**Issue by kaciker** [lavinir/hassio-onedrive-backup#89]
Hello
Just I installed the addon in my Home Assistant 2023.5.3.
Everything was ok, I got permissiona to my Ondrive account after linkt ik, but the addon is stopped in Initializing..

The log show several mentions to "Microsoft.Graph.ServiceException: Code: accessDenied" 

<img width="1356" alt="image" src="https://github.com/lavinir/hassio-onedrive-backup/assets/7668181/a4f5f0e5-205b-443a-b3ea-37642d72d8b2">

This is the log in verbose mode.

05/17/2023 10:51:26 [8] Info: Backup interval configured to every 72 hours
05/17/2023 10:51:26 [8] Info: File Sync Disabled
05/17/2023 10:51:28 [8] Error: Error getting free space: Status Code: Forbidden
Microsoft.Graph.ServiceException: Code: accessDenied
Message: Access denied
Inner error:
	AdditionalData:
	date: 2023-05-17T08:51:28
	request-id: 11acc314-3803-4b26-b20b-f2ede9031ff1
	client-request-id: 11acc314-3803-4b26-b20b-f2ede9031ff1
ClientRequestId: 11acc314-3803-4b26-b20b-f2ede9031ff1
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.DriveRequest.GetAsync(CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetFreeSpaceInGB() in /src/Graph/GraphHelper.cs:line 215
05/17/2023 10:51:28 [8] Error: Unexpected error. System.NullReferenceException: Object reference not set to an instance of an object.
   at hassio_onedrive_backup.Hass.HassOnedriveFreeSpaceEntityState.UpdateOneDriveFreespaceSensorInHass(OneDriveFreeSpaceData freeSpaceData) in /src/Hass/HassOnedriveFreeSpaceEntityState.cs:line 29
   at hassio_onedrive_backup.Orchestrator.Start() in /src/Orchestrator.cs:line 77

**Comment by kaciker** [comment]
To mention that the account that I want to link is a deveolper account. I had no issues to link with rclone, and sync drives. I'm not sure if this is part or the root cause of my problem

**Comment by lavinir** [comment]
Hi,

What do you mean a developer account ? This requires a personal MS account. Work / School account (OneDrive for business) is not supported.

**Comment by hayvan96** [comment]
Hi I have the same issue, with a personal account, on 2023.04.6

Seems to have stopped backing up yesterday or two days ago. No upgrades on my system, a reboot didn't change anything. Maybe something  changed on MS's side?

**Comment by lavinir** [comment]
Maybe something in the token was revoked. Coudl you try to uninstall and reinstall see if this still happens so we rule out anything API related ?

**Comment by hayvan96** [comment]
> Maybe something in the token was revoked. Coudl you try to uninstall and reinstall see if this still happens so we rule out anything API related ?

uninstall and reinstalling fixed it me for me (so far).
